[Sun Mar 13 16:07:11.717796 2022] [wsgi:error] [pid 15312:tid 140043750422272] [client 123.203.49.113:54644] mod_wsgi (pid=15312): Failed to exec Python script file '/var/www/html/app.wsgi'.
[Sun Mar 13 16:07:11.717870 2022] [wsgi:error] [pid 15312:tid 140043750422272] [client 123.203.49.113:54644] mod_wsgi (pid=15312): Exception occurred processing WSGI script '/var/www/html/app.wsgi'.
[Sun Mar 13 16:07:11.718117 2022] [wsgi:error] [pid 15312:tid 140043750422272] [client 123.203.49.113:54644] Traceback (most recent call last):
[Sun Mar 13 16:07:11.718142 2022] [wsgi:error] [pid 15312:tid 140043750422272] [client 123.203.49.113:54644]   File "/var/www/html/app.wsgi", line 3, in <module>
[Sun Mar 13 16:07:11.718146 2022] [wsgi:error] [pid 15312:tid 140043750422272] [client 123.203.49.113:54644]     from init import app as application
[Sun Mar 13 16:07:11.718152 2022] [wsgi:error] [pid 15312:tid 140043750422272] [client 123.203.49.113:54644]   File "/var/www/html/init.py", line 2, in <module>
[Sun Mar 13 16:07:11.718156 2022] [wsgi:error] [pid 15312:tid 140043750422272] [client 123.203.49.113:54644]     from flask_mysqldb import MySQL
[Sun Mar 13 16:07:11.718168 2022] [wsgi:error] [pid 15312:tid 140043750422272] [client 123.203.49.113:54644] ModuleNotFoundError: No module named 'flask_mysqldb'
[Sun Mar 13 16:07:12.084538 2022] [wsgi:error] [pid 15313:tid 140043792385792] [client 123.203.49.113:54645] mod_wsgi (pid=15313): Failed to exec Python script file '/var/www/html/app.wsgi'., referer: http://ec2-18-163-100-14.ap-east-1.compute.amazonaws.com/
[Sun Mar 13 16:07:12.084605 2022] [wsgi:error] [pid 15313:tid 140043792385792] [client 123.203.49.113:54645] mod_wsgi (pid=15313): Exception occurred processing WSGI script '/var/www/html/app.wsgi'., referer: http://ec2-18-163-100-14.ap-east-1.compute.amazonaws.com/
[Sun Mar 13 16:07:12.084850 2022] [wsgi:error] [pid 15313:tid 140043792385792] [client 123.203.49.113:54645] Traceback (most recent call last):, referer: http://ec2-18-163-100-14.ap-east-1.compute.amazonaws.com/
[Sun Mar 13 16:07:12.084876 2022] [wsgi:error] [pid 15313:tid 140043792385792] [client 123.203.49.113:54645]   File "/var/www/html/app.wsgi", line 3, in <module>, referer: http://ec2-18-163-100-14.ap-east-1.compute.amazonaws.com/
[Sun Mar 13 16:07:12.084881 2022] [wsgi:error] [pid 15313:tid 140043792385792] [client 123.203.49.113:54645]     from init import app as application, referer: http://ec2-18-163-100-14.ap-east-1.compute.amazonaws.com/
[Sun Mar 13 16:07:12.084887 2022] [wsgi:error] [pid 15313:tid 140043792385792] [client 123.203.49.113:54645]   File "/var/www/html/init.py", line 2, in <module>, referer: http://ec2-18-163-100-14.ap-east-1.compute.amazonaws.com/
[Sun Mar 13 16:07:12.084891 2022] [wsgi:error] [pid 15313:tid 140043792385792] [client 123.203.49.113:54645]     from flask_mysqldb import MySQL, referer: http://ec2-18-163-100-14.ap-east-1.compute.amazonaws.com/
[Sun Mar 13 16:07:12.084903 2022] [wsgi:error] [pid 15313:tid 140043792385792] [client 123.203.49.113:54645] ModuleNotFoundError: No module named 'flask_mysqldb', referer: http://ec2-18-163-100-14.ap-east-1.compute.amazonaws.com/
[Sun Mar 13 16:09:33.923317 2022] [wsgi:error] [pid 15312:tid 140043851134720] [client 123.203.49.113:54724] mod_wsgi (pid=15312): Failed to exec Python script file '/var/www/html/app.wsgi'.
[Sun Mar 13 16:09:33.923378 2022] [wsgi:error] [pid 15312:tid 140043851134720] [client 123.203.49.113:54724] mod_wsgi (pid=15312): Exception occurred processing WSGI script '/var/www/html/app.wsgi'.
[Sun Mar 13 16:09:33.923550 2022] [wsgi:error] [pid 15312:tid 140043851134720] [client 123.203.49.113:54724] Traceback (most recent call last):
[Sun Mar 13 16:09:33.923591 2022] [wsgi:error] [pid 15312:tid 140043851134720] [client 123.203.49.113:54724]   File "/var/www/html/app.wsgi", line 3, in <module>
[Sun Mar 13 16:09:33.923595 2022] [wsgi:error] [pid 15312:tid 140043851134720] [client 123.203.49.113:54724]     from init import app as application
[Sun Mar 13 16:09:33.923601 2022] [wsgi:error] [pid 15312:tid 140043851134720] [client 123.203.49.113:54724]   File "/var/www/html/init.py", line 2, in <module>
[Sun Mar 13 16:09:33.923612 2022] [wsgi:error] [pid 15312:tid 140043851134720] [client 123.203.49.113:54724]     from flask_mysqldb import MySQL
[Sun Mar 13 16:09:33.923627 2022] [wsgi:error] [pid 15312:tid 140043851134720] [client 123.203.49.113:54724] ModuleNotFoundError: No module named 'flask_mysqldb'
[Sun Mar 13 16:09:34.111252 2022] [wsgi:error] [pid 15313:tid 140043716851456] [client 123.203.49.113:54725] mod_wsgi (pid=15313): Failed to exec Python script file '/var/www/html/app.wsgi'., referer: http://ec2-18-163-100-14.ap-east-1.compute.amazonaws.com/
[Sun Mar 13 16:09:34.111314 2022] [wsgi:error] [pid 15313:tid 140043716851456] [client 123.203.49.113:54725] mod_wsgi (pid=15313): Exception occurred processing WSGI script '/var/www/html/app.wsgi'., referer: http://ec2-18-163-100-14.ap-east-1.compute.amazonaws.com/
[Sun Mar 13 16:09:34.111392 2022] [wsgi:error] [pid 15313:tid 140043716851456] [client 123.203.49.113:54725] Traceback (most recent call last):, referer: http://ec2-18-163-100-14.ap-east-1.compute.amazonaws.com/
[Sun Mar 13 16:09:34.111415 2022] [wsgi:error] [pid 15313:tid 140043716851456] [client 123.203.49.113:54725]   File "/var/www/html/app.wsgi", line 3, in <module>, referer: http://ec2-18-163-100-14.ap-east-1.compute.amazonaws.com/
[Sun Mar 13 16:09:34.111419 2022] [wsgi:error] [pid 15313:tid 140043716851456] [client 123.203.49.113:54725]     from init import app as application, referer: http://ec2-18-163-100-14.ap-east-1.compute.amazonaws.com/
[Sun Mar 13 16:09:34.111426 2022] [wsgi:error] [pid 15313:tid 140043716851456] [client 123.203.49.113:54725]   File "/var/www/html/init.py", line 2, in <module>, referer: http://ec2-18-163-100-14.ap-east-1.compute.amazonaws.com/
[Sun Mar 13 16:09:34.111430 2022] [wsgi:error] [pid 15313:tid 140043716851456] [client 123.203.49.113:54725]     from flask_mysqldb import MySQL, referer: http://ec2-18-163-100-14.ap-east-1.compute.amazonaws.com/
[Sun Mar 13 16:09:34.111443 2022] [wsgi:error] [pid 15313:tid 140043716851456] [client 123.203.49.113:54725] ModuleNotFoundError: No module named 'flask_mysqldb', referer: http://ec2-18-163-100-14.ap-east-1.compute.amazonaws.com/
[Sun Mar 13 16:09:58.016656 2022] [wsgi:error] [pid 15956:tid 139837004830464] [client 123.203.49.113:54739] mod_wsgi (pid=15956): Failed to exec Python script file '/var/www/html/app.wsgi'.
[Sun Mar 13 16:09:58.016755 2022] [wsgi:error] [pid 15956:tid 139837004830464] [client 123.203.49.113:54739] mod_wsgi (pid=15956): Exception occurred processing WSGI script '/var/www/html/app.wsgi'.
[Sun Mar 13 16:09:58.017016 2022] [wsgi:error] [pid 15956:tid 139837004830464] [client 123.203.49.113:54739] Traceback (most recent call last):
[Sun Mar 13 16:09:58.017043 2022] [wsgi:error] [pid 15956:tid 139837004830464] [client 123.203.49.113:54739]   File "/var/www/html/app.wsgi", line 3, in <module>
[Sun Mar 13 16:09:58.017047 2022] [wsgi:error] [pid 15956:tid 139837004830464] [client 123.203.49.113:54739]     from init import app as application
[Sun Mar 13 16:09:58.017054 2022] [wsgi:error] [pid 15956:tid 139837004830464] [client 123.203.49.113:54739]   File "/var/www/html/init.py", line 2, in <module>
[Sun Mar 13 16:09:58.017057 2022] [wsgi:error] [pid 15956:tid 139837004830464] [client 123.203.49.113:54739]     from flask_mysqldb import MySQL
[Sun Mar 13 16:09:58.017071 2022] [wsgi:error] [pid 15956:tid 139837004830464] [client 123.203.49.113:54739] ModuleNotFoundError: No module named 'flask_mysqldb'
[Sun Mar 13 16:09:58.436514 2022] [wsgi:error] [pid 15957:tid 139837004830464] [client 123.203.49.113:54740] mod_wsgi (pid=15957): Failed to exec Python script file '/var/www/html/app.wsgi'., referer: http://ec2-18-163-100-14.ap-east-1.compute.amazonaws.com/
[Sun Mar 13 16:09:58.436581 2022] [wsgi:error] [pid 15957:tid 139837004830464] [client 123.203.49.113:54740] mod_wsgi (pid=15957): Exception occurred processing WSGI script '/var/www/html/app.wsgi'., referer: http://ec2-18-163-100-14.ap-east-1.compute.amazonaws.com/
[Sun Mar 13 16:09:58.436829 2022] [wsgi:error] [pid 15957:tid 139837004830464] [client 123.203.49.113:54740] Traceback (most recent call last):, referer: http://ec2-18-163-100-14.ap-east-1.compute.amazonaws.com/
[Sun Mar 13 16:09:58.436865 2022] [wsgi:error] [pid 15957:tid 139837004830464] [client 123.203.49.113:54740]   File "/var/www/html/app.wsgi", line 3, in <module>, referer: http://ec2-18-163-100-14.ap-east-1.compute.amazonaws.com/
[Sun Mar 13 16:09:58.436869 2022] [wsgi:error] [pid 15957:tid 139837004830464] [client 123.203.49.113:54740]     from init import app as application, referer: http://ec2-18-163-100-14.ap-east-1.compute.amazonaws.com/
[Sun Mar 13 16:09:58.436876 2022] [wsgi:error] [pid 15957:tid 139837004830464] [client 123.203.49.113:54740]   File "/var/www/html/init.py", line 2, in <module>, referer: http://ec2-18-163-100-14.ap-east-1.compute.amazonaws.com/
[Sun Mar 13 16:09:58.436880 2022] [wsgi:error] [pid 15957:tid 139837004830464] [client 123.203.49.113:54740]     from flask_mysqldb import MySQL, referer: http://ec2-18-163-100-14.ap-east-1.compute.amazonaws.com/
[Sun Mar 13 16:09:58.436893 2022] [wsgi:error] [pid 15957:tid 139837004830464] [client 123.203.49.113:54740] ModuleNotFoundError: No module named 'flask_mysqldb', referer: http://ec2-18-163-100-14.ap-east-1.compute.amazonaws.com/
[Sun Mar 13 16:10:15.473745 2022] [wsgi:error] [pid 16033:tid 140402556372736] [client 123.203.49.113:54750] mod_wsgi (pid=16033): Failed to exec Python script file '/var/www/html/app.wsgi'.
[Sun Mar 13 16:10:15.473824 2022] [wsgi:error] [pid 16033:tid 140402556372736] [client 123.203.49.113:54750] mod_wsgi (pid=16033): Exception occurred processing WSGI script '/var/www/html/app.wsgi'.
[Sun Mar 13 16:10:15.474090 2022] [wsgi:error] [pid 16033:tid 140402556372736] [client 123.203.49.113:54750] Traceback (most recent call last):
[Sun Mar 13 16:10:15.474115 2022] [wsgi:error] [pid 16033:tid 140402556372736] [client 123.203.49.113:54750]   File "/var/www/html/app.wsgi", line 3, in <module>
[Sun Mar 13 16:10:15.474119 2022] [wsgi:error] [pid 16033:tid 140402556372736] [client 123.203.49.113:54750]     from init import app as application
[Sun Mar 13 16:10:15.474126 2022] [wsgi:error] [pid 16033:tid 140402556372736] [client 123.203.49.113:54750]   File "/var/www/html/init.py", line 2, in <module>
[Sun Mar 13 16:10:15.474130 2022] [wsgi:error] [pid 16033:tid 140402556372736] [client 123.203.49.113:54750]     from flask_mysqldb import MySQL
[Sun Mar 13 16:10:15.474143 2022] [wsgi:error] [pid 16033:tid 140402556372736] [client 123.203.49.113:54750] ModuleNotFoundError: No module named 'flask_mysqldb'
[Sun Mar 13 16:10:15.689184 2022] [wsgi:error] [pid 16033:tid 140402539587328] [client 123.203.49.113:54752] mod_wsgi (pid=16033): Failed to exec Python script file '/var/www/html/app.wsgi'., referer: http://ec2-18-163-100-14.ap-east-1.compute.amazonaws.com/
[Sun Mar 13 16:10:15.689229 2022] [wsgi:error] [pid 16033:tid 140402539587328] [client 123.203.49.113:54752] mod_wsgi (pid=16033): Exception occurred processing WSGI script '/var/www/html/app.wsgi'., referer: http://ec2-18-163-100-14.ap-east-1.compute.amazonaws.com/
[Sun Mar 13 16:10:15.689304 2022] [wsgi:error] [pid 16033:tid 140402539587328] [client 123.203.49.113:54752] Traceback (most recent call last):, referer: http://ec2-18-163-100-14.ap-east-1.compute.amazonaws.com/
[Sun Mar 13 16:10:15.689326 2022] [wsgi:error] [pid 16033:tid 140402539587328] [client 123.203.49.113:54752]   File "/var/www/html/app.wsgi", line 3, in <module>, referer: http://ec2-18-163-100-14.ap-east-1.compute.amazonaws.com/
[Sun Mar 13 16:10:15.689331 2022] [wsgi:error] [pid 16033:tid 140402539587328] [client 123.203.49.113:54752]     from init import app as application, referer: http://ec2-18-163-100-14.ap-east-1.compute.amazonaws.com/
[Sun Mar 13 16:10:15.689337 2022] [wsgi:error] [pid 16033:tid 140402539587328] [client 123.203.49.113:54752]   File "/var/www/html/init.py", line 2, in <module>, referer: http://ec2-18-163-100-14.ap-east-1.compute.amazonaws.com/
[Sun Mar 13 16:10:15.689341 2022] [wsgi:error] [pid 16033:tid 140402539587328] [client 123.203.49.113:54752]     from flask_mysqldb import MySQL, referer: http://ec2-18-163-100-14.ap-east-1.compute.amazonaws.com/
[Sun Mar 13 16:10:15.689362 2022] [wsgi:error] [pid 16033:tid 140402539587328] [client 123.203.49.113:54752] ModuleNotFoundError: No module named 'flask_mysqldb', referer: http://ec2-18-163-100-14.ap-east-1.compute.amazonaws.com/
[Sun Mar 13 16:10:37.440695 2022] [wsgi:error] [pid 16033:tid 140402522801920] [client 123.203.49.113:54769] mod_wsgi (pid=16033): Failed to exec Python script file '/var/www/html/app.wsgi'.
[Sun Mar 13 16:10:37.440739 2022] [wsgi:error] [pid 16033:tid 140402522801920] [client 123.203.49.113:54769] mod_wsgi (pid=16033): Exception occurred processing WSGI script '/var/www/html/app.wsgi'.
[Sun Mar 13 16:10:37.440811 2022] [wsgi:error] [pid 16033:tid 140402522801920] [client 123.203.49.113:54769] Traceback (most recent call last):
[Sun Mar 13 16:10:37.440838 2022] [wsgi:error] [pid 16033:tid 140402522801920] [client 123.203.49.113:54769]   File "/var/www/html/app.wsgi", line 3, in <module>
[Sun Mar 13 16:10:37.440843 2022] [wsgi:error] [pid 16033:tid 140402522801920] [client 123.203.49.113:54769]     from init import app as application
[Sun Mar 13 16:10:37.440849 2022] [wsgi:error] [pid 16033:tid 140402522801920] [client 123.203.49.113:54769]   File "/var/www/html/init.py", line 3, in <module>
[Sun Mar 13 16:10:37.440852 2022] [wsgi:error] [pid 16033:tid 140402522801920] [client 123.203.49.113:54769]     from wtforms import Form, StringField, TextAreaField, PasswordField, validators
[Sun Mar 13 16:10:37.440866 2022] [wsgi:error] [pid 16033:tid 140402522801920] [client 123.203.49.113:54769] ModuleNotFoundError: No module named 'wtforms'
[Sun Mar 13 16:10:37.864295 2022] [wsgi:error] [pid 16032:tid 140402723940096] [client 123.203.49.113:54770] mod_wsgi (pid=16032): Failed to exec Python script file '/var/www/html/app.wsgi'., referer: http://ec2-18-163-100-14.ap-east-1.compute.amazonaws.com/
[Sun Mar 13 16:10:37.864358 2022] [wsgi:error] [pid 16032:tid 140402723940096] [client 123.203.49.113:54770] mod_wsgi (pid=16032): Exception occurred processing WSGI script '/var/www/html/app.wsgi'., referer: http://ec2-18-163-100-14.ap-east-1.compute.amazonaws.com/
[Sun Mar 13 16:10:37.864617 2022] [wsgi:error] [pid 16032:tid 140402723940096] [client 123.203.49.113:54770] Traceback (most recent call last):, referer: http://ec2-18-163-100-14.ap-east-1.compute.amazonaws.com/
[Sun Mar 13 16:10:37.864649 2022] [wsgi:error] [pid 16032:tid 140402723940096] [client 123.203.49.113:54770]   File "/var/www/html/app.wsgi", line 3, in <module>, referer: http://ec2-18-163-100-14.ap-east-1.compute.amazonaws.com/
[Sun Mar 13 16:10:37.864654 2022] [wsgi:error] [pid 16032:tid 140402723940096] [client 123.203.49.113:54770]     from init import app as application, referer: http://ec2-18-163-100-14.ap-east-1.compute.amazonaws.com/
[Sun Mar 13 16:10:37.864660 2022] [wsgi:error] [pid 16032:tid 140402723940096] [client 123.203.49.113:54770]   File "/var/www/html/init.py", line 3, in <module>, referer: http://ec2-18-163-100-14.ap-east-1.compute.amazonaws.com/
[Sun Mar 13 16:10:37.864664 2022] [wsgi:error] [pid 16032:tid 140402723940096] [client 123.203.49.113:54770]     from wtforms import Form, StringField, TextAreaField, PasswordField, validators, referer: http://ec2-18-163-100-14.ap-east-1.compute.amazonaws.com/
[Sun Mar 13 16:10:37.864678 2022] [wsgi:error] [pid 16032:tid 140402723940096] [client 123.203.49.113:54770] ModuleNotFoundError: No module named 'wtforms', referer: http://ec2-18-163-100-14.ap-east-1.compute.amazonaws.com/
[Wed Mar 23 14:51:32.323771 2022] [wsgi:error] [pid 1478:tid 140136285185792] [client 123.203.49.113:62404] mod_wsgi (pid=1478): Failed to exec Python script file '/var/www/html/app.wsgi'.
[Wed Mar 23 14:51:32.324288 2022] [wsgi:error] [pid 1478:tid 140136285185792] [client 123.203.49.113:62404] mod_wsgi (pid=1478): Exception occurred processing WSGI script '/var/www/html/app.wsgi'.
[Wed Mar 23 14:51:32.324569 2022] [wsgi:error] [pid 1478:tid 140136285185792] [client 123.203.49.113:62404] Traceback (most recent call last):
[Wed Mar 23 14:51:32.324604 2022] [wsgi:error] [pid 1478:tid 140136285185792] [client 123.203.49.113:62404]   File "/var/www/html/app.wsgi", line 3, in <module>
[Wed Mar 23 14:51:32.324609 2022] [wsgi:error] [pid 1478:tid 140136285185792] [client 123.203.49.113:62404]     from init import app as application
[Wed Mar 23 14:51:32.324615 2022] [wsgi:error] [pid 1478:tid 140136285185792] [client 123.203.49.113:62404]   File "/var/www/html/init.py", line 3, in <module>
[Wed Mar 23 14:51:32.324618 2022] [wsgi:error] [pid 1478:tid 140136285185792] [client 123.203.49.113:62404]     from flask_restful import Api, Resource
[Wed Mar 23 14:51:32.324632 2022] [wsgi:error] [pid 1478:tid 140136285185792] [client 123.203.49.113:62404] ModuleNotFoundError: No module named 'flask_restful'
[Wed Mar 23 14:51:51.123026 2022] [wsgi:error] [pid 1478:tid 140136251614976] [client 123.203.49.113:62407] [2022-03-23 14:51:51,117] ERROR in app: Exception on / [GET]
[Wed Mar 23 14:51:51.123047 2022] [wsgi:error] [pid 1478:tid 140136251614976] [client 123.203.49.113:62407] Traceback (most recent call last):
[Wed Mar 23 14:51:51.123050 2022] [wsgi:error] [pid 1478:tid 140136251614976] [client 123.203.49.113:62407]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app
[Wed Mar 23 14:51:51.123054 2022] [wsgi:error] [pid 1478:tid 140136251614976] [client 123.203.49.113:62407]     response = self.full_dispatch_request()
[Wed Mar 23 14:51:51.123057 2022] [wsgi:error] [pid 1478:tid 140136251614976] [client 123.203.49.113:62407]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request
[Wed Mar 23 14:51:51.123060 2022] [wsgi:error] [pid 1478:tid 140136251614976] [client 123.203.49.113:62407]     rv = self.handle_user_exception(e)
[Wed Mar 23 14:51:51.123063 2022] [wsgi:error] [pid 1478:tid 140136251614976] [client 123.203.49.113:62407]   File "/usr/local/lib/python3.8/dist-packages/flask_restful/__init__.py", line 271, in error_router
[Wed Mar 23 14:51:51.123066 2022] [wsgi:error] [pid 1478:tid 140136251614976] [client 123.203.49.113:62407]     return original_handler(e)
[Wed Mar 23 14:51:51.123069 2022] [wsgi:error] [pid 1478:tid 140136251614976] [client 123.203.49.113:62407]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request
[Wed Mar 23 14:51:51.123072 2022] [wsgi:error] [pid 1478:tid 140136251614976] [client 123.203.49.113:62407]     rv = self.dispatch_request()
[Wed Mar 23 14:51:51.123075 2022] [wsgi:error] [pid 1478:tid 140136251614976] [client 123.203.49.113:62407]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request
[Wed Mar 23 14:51:51.123079 2022] [wsgi:error] [pid 1478:tid 140136251614976] [client 123.203.49.113:62407]     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
[Wed Mar 23 14:51:51.123082 2022] [wsgi:error] [pid 1478:tid 140136251614976] [client 123.203.49.113:62407]   File "/var/www/html/init.py", line 24, in home
[Wed Mar 23 14:51:51.123085 2022] [wsgi:error] [pid 1478:tid 140136251614976] [client 123.203.49.113:62407]     return render_template('home.html')
[Wed Mar 23 14:51:51.123088 2022] [wsgi:error] [pid 1478:tid 140136251614976] [client 123.203.49.113:62407]   File "/usr/local/lib/python3.8/dist-packages/flask/templating.py", line 148, in render_template
[Wed Mar 23 14:51:51.123091 2022] [wsgi:error] [pid 1478:tid 140136251614976] [client 123.203.49.113:62407]     ctx.app.jinja_env.get_or_select_template(template_name_or_list),
[Wed Mar 23 14:51:51.123094 2022] [wsgi:error] [pid 1478:tid 140136251614976] [client 123.203.49.113:62407]   File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 1068, in get_or_select_template
[Wed Mar 23 14:51:51.123097 2022] [wsgi:error] [pid 1478:tid 140136251614976] [client 123.203.49.113:62407]     return self.get_template(template_name_or_list, parent, globals)
[Wed Mar 23 14:51:51.123100 2022] [wsgi:error] [pid 1478:tid 140136251614976] [client 123.203.49.113:62407]   File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 997, in get_template
[Wed Mar 23 14:51:51.123110 2022] [wsgi:error] [pid 1478:tid 140136251614976] [client 123.203.49.113:62407]     return self._load_template(name, globals)
[Wed Mar 23 14:51:51.123113 2022] [wsgi:error] [pid 1478:tid 140136251614976] [client 123.203.49.113:62407]   File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 958, in _load_template
[Wed Mar 23 14:51:51.123116 2022] [wsgi:error] [pid 1478:tid 140136251614976] [client 123.203.49.113:62407]     template = self.loader.load(self, name, self.make_globals(globals))
[Wed Mar 23 14:51:51.123119 2022] [wsgi:error] [pid 1478:tid 140136251614976] [client 123.203.49.113:62407]   File "/usr/local/lib/python3.8/dist-packages/jinja2/loaders.py", line 125, in load
[Wed Mar 23 14:51:51.123122 2022] [wsgi:error] [pid 1478:tid 140136251614976] [client 123.203.49.113:62407]     source, filename, uptodate = self.get_source(environment, name)
[Wed Mar 23 14:51:51.123125 2022] [wsgi:error] [pid 1478:tid 140136251614976] [client 123.203.49.113:62407]   File "/usr/local/lib/python3.8/dist-packages/flask/templating.py", line 59, in get_source
[Wed Mar 23 14:51:51.123128 2022] [wsgi:error] [pid 1478:tid 140136251614976] [client 123.203.49.113:62407]     return self._get_source_fast(environment, template)
[Wed Mar 23 14:51:51.123131 2022] [wsgi:error] [pid 1478:tid 140136251614976] [client 123.203.49.113:62407]   File "/usr/local/lib/python3.8/dist-packages/flask/templating.py", line 95, in _get_source_fast
[Wed Mar 23 14:51:51.123134 2022] [wsgi:error] [pid 1478:tid 140136251614976] [client 123.203.49.113:62407]     raise TemplateNotFound(template)
[Wed Mar 23 14:51:51.123137 2022] [wsgi:error] [pid 1478:tid 140136251614976] [client 123.203.49.113:62407] jinja2.exceptions.TemplateNotFound: home.html
[Wed Mar 23 15:32:59.028708 2022] [wsgi:error] [pid 2102:tid 140206179051264] [client 123.203.49.113:50991] mod_wsgi (pid=2102): Failed to exec Python script file '/var/www/html/app.wsgi'., referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/product_003
[Wed Mar 23 15:32:59.028751 2022] [wsgi:error] [pid 2102:tid 140206179051264] [client 123.203.49.113:50991] mod_wsgi (pid=2102): Exception occurred processing WSGI script '/var/www/html/app.wsgi'., referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/product_003
[Wed Mar 23 15:32:59.032584 2022] [wsgi:error] [pid 2102:tid 140206179051264] [client 123.203.49.113:50991] Traceback (most recent call last):, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/product_003
[Wed Mar 23 15:32:59.032614 2022] [wsgi:error] [pid 2102:tid 140206179051264] [client 123.203.49.113:50991]   File "/var/www/html/app.wsgi", line 3, in <module>, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/product_003
[Wed Mar 23 15:32:59.032619 2022] [wsgi:error] [pid 2102:tid 140206179051264] [client 123.203.49.113:50991]     from init import app as application, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/product_003
[Wed Mar 23 15:32:59.032629 2022] [wsgi:error] [pid 2102:tid 140206179051264] [client 123.203.49.113:50991]   File "/var/www/html/init.py", line 25, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/product_003
[Wed Mar 23 15:32:59.032637 2022] [wsgi:error] [pid 2102:tid 140206179051264] [client 123.203.49.113:50991]     print(f.read()), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/product_003
[Wed Mar 23 15:32:59.032651 2022] [wsgi:error] [pid 2102:tid 140206179051264] [client 123.203.49.113:50991]                   ^, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/product_003
[Wed Mar 23 15:32:59.032658 2022] [wsgi:error] [pid 2102:tid 140206179051264] [client 123.203.49.113:50991] IndentationError: unindent does not match any outer indentation level, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/product_003
[Wed Mar 23 15:34:58.013096 2022] [wsgi:error] [pid 2250:tid 139732516263680] [client 123.203.49.113:51070] {"1":{"Id":"1","Name":"Frying Pan","Price":"149.9","Description":"Frying pan, stainless steel/non-stick coating","Date":"28/1/2022","Quantity":"12150","Image":"1.jpg"},"2":{"Id":"2","Name":"TOFTBYN","Price":"749","Description":"Mirror, ash effect/brown","Date":"28/1/2022","Quantity":"170","Image":"2.jpg"},"3":{"Id":"3","Name":"LAPPNYCKLAR","Price":"329.9","Description":"Duvet cover and 2 pillowcases, white/multicolour","Date":"28/1/2022","Quantity":"30","Image":"/static/"},"4":{"Id":"4","Name":"VAXBO","Price":"39","Description":"Collage frame for 8 photos, black","Date":"28/01/2022","Quantity":"15","Image":"/static/"},"5":{"Id":"5","Name":"Table","Price":"100","Description":"4 legged","Date":"16/02/2022","Quantity":"20","Image":"/static/"}}
[Wed Mar 23 15:35:38.645296 2022] [wsgi:error] [pid 2249:tid 139732549834496] [client 123.203.49.113:64946] {"1":{"Id":"1","Name":"Frying Pan","Price":"149.9","Description":"Frying pan, stainless steel/non-stick coating","Date":"28/1/2022","Quantity":"12150","Image":"1.jpg"},"2":{"Id":"2","Name":"TOFTBYN","Price":"749","Description":"Mirror, ash effect/brown","Date":"28/1/2022","Quantity":"170","Image":"2.jpg"},"3":{"Id":"3","Name":"LAPPNYCKLAR","Price":"329.9","Description":"Duvet cover and 2 pillowcases, white/multicolour","Date":"28/1/2022","Quantity":"30","Image":"/static/"},"4":{"Id":"4","Name":"VAXBO","Price":"39","Description":"Collage frame for 8 photos, black","Date":"28/01/2022","Quantity":"15","Image":"/static/"},"5":{"Id":"5","Name":"Table","Price":"100","Description":"4 legged","Date":"16/02/2022","Quantity":"20","Image":"/static/"}}
[Wed Mar 23 15:36:39.369116 2022] [wsgi:error] [pid 2250:tid 139732650546944] [client 123.203.49.113:51128] {"1":{"Id":"1","Name":"Frying Pan","Price":"149.9","Description":"Frying pan, stainless steel/non-stick coating","Date":"28/1/2022","Quantity":"12150","Image":"1.jpg"},"2":{"Id":"2","Name":"TOFTBYN","Price":"749","Description":"Mirror, ash effect/brown","Date":"28/1/2022","Quantity":"170","Image":"2.jpg"},"3":{"Id":"3","Name":"LAPPNYCKLAR","Price":"329.9","Description":"Duvet cover and 2 pillowcases, white/multicolour","Date":"28/1/2022","Quantity":"30","Image":"/static/"},"4":{"Id":"4","Name":"VAXBO","Price":"39","Description":"Collage frame for 8 photos, black","Date":"28/01/2022","Quantity":"15","Image":"/static/"},"5":{"Id":"5","Name":"Table","Price":"100","Description":"4 legged","Date":"16/02/2022","Quantity":"20","Image":"/static/"}}
[Wed Mar 23 15:36:52.218661 2022] [wsgi:error] [pid 2250:tid 139732591798016] [client 151.233.51.53:52561] {"1":{"Id":"1","Name":"Frying Pan","Price":"149.9","Description":"Frying pan, stainless steel/non-stick coating","Date":"28/1/2022","Quantity":"12150","Image":"1.jpg"},"2":{"Id":"2","Name":"TOFTBYN","Price":"749","Description":"Mirror, ash effect/brown","Date":"28/1/2022","Quantity":"170","Image":"2.jpg"},"3":{"Id":"3","Name":"LAPPNYCKLAR","Price":"329.9","Description":"Duvet cover and 2 pillowcases, white/multicolour","Date":"28/1/2022","Quantity":"30","Image":"/static/"},"4":{"Id":"4","Name":"VAXBO","Price":"39","Description":"Collage frame for 8 photos, black","Date":"28/01/2022","Quantity":"15","Image":"/static/"},"5":{"Id":"5","Name":"Table","Price":"100","Description":"4 legged","Date":"16/02/2022","Quantity":"20","Image":"/static/"}}
[Wed Mar 23 16:00:18.006029 2022] [wsgi:error] [pid 3391:tid 139756465768192] [client 123.203.49.113:65033] [2022-03-23 16:00:18,003] ERROR in app: Exception on /register [POST], referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/register
[Wed Mar 23 16:00:18.006062 2022] [wsgi:error] [pid 3391:tid 139756465768192] [client 123.203.49.113:65033] Traceback (most recent call last):, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/register
[Wed Mar 23 16:00:18.006066 2022] [wsgi:error] [pid 3391:tid 139756465768192] [client 123.203.49.113:65033]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/register
[Wed Mar 23 16:00:18.006077 2022] [wsgi:error] [pid 3391:tid 139756465768192] [client 123.203.49.113:65033]     response = self.full_dispatch_request(), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/register
[Wed Mar 23 16:00:18.006080 2022] [wsgi:error] [pid 3391:tid 139756465768192] [client 123.203.49.113:65033]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/register
[Wed Mar 23 16:00:18.006083 2022] [wsgi:error] [pid 3391:tid 139756465768192] [client 123.203.49.113:65033]     rv = self.handle_user_exception(e), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/register
[Wed Mar 23 16:00:18.006086 2022] [wsgi:error] [pid 3391:tid 139756465768192] [client 123.203.49.113:65033]   File "/usr/local/lib/python3.8/dist-packages/flask_restful/__init__.py", line 271, in error_router, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/register
[Wed Mar 23 16:00:18.006090 2022] [wsgi:error] [pid 3391:tid 139756465768192] [client 123.203.49.113:65033]     return original_handler(e), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/register
[Wed Mar 23 16:00:18.006093 2022] [wsgi:error] [pid 3391:tid 139756465768192] [client 123.203.49.113:65033]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/register
[Wed Mar 23 16:00:18.006096 2022] [wsgi:error] [pid 3391:tid 139756465768192] [client 123.203.49.113:65033]     rv = self.dispatch_request(), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/register
[Wed Mar 23 16:00:18.006099 2022] [wsgi:error] [pid 3391:tid 139756465768192] [client 123.203.49.113:65033]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/register
[Wed Mar 23 16:00:18.006102 2022] [wsgi:error] [pid 3391:tid 139756465768192] [client 123.203.49.113:65033]     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/register
[Wed Mar 23 16:00:18.006105 2022] [wsgi:error] [pid 3391:tid 139756465768192] [client 123.203.49.113:65033]   File "/var/www/html/init.py", line 51, in register, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/register
[Wed Mar 23 16:00:18.006108 2022] [wsgi:error] [pid 3391:tid 139756465768192] [client 123.203.49.113:65033]     cur = mysql.connection.cursor(), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/register
[Wed Mar 23 16:00:18.006111 2022] [wsgi:error] [pid 3391:tid 139756465768192] [client 123.203.49.113:65033]   File "/usr/local/lib/python3.8/dist-packages/flask_mysqldb/__init__.py", line 101, in connection, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/register
[Wed Mar 23 16:00:18.006115 2022] [wsgi:error] [pid 3391:tid 139756465768192] [client 123.203.49.113:65033]     ctx.mysql_db = self.connect, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/register
[Wed Mar 23 16:00:18.006118 2022] [wsgi:error] [pid 3391:tid 139756465768192] [client 123.203.49.113:65033]   File "/usr/local/lib/python3.8/dist-packages/flask_mysqldb/__init__.py", line 88, in connect, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/register
[Wed Mar 23 16:00:18.006121 2022] [wsgi:error] [pid 3391:tid 139756465768192] [client 123.203.49.113:65033]     return MySQLdb.connect(**kwargs), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/register
[Wed Mar 23 16:00:18.006124 2022] [wsgi:error] [pid 3391:tid 139756465768192] [client 123.203.49.113:65033]   File "/usr/local/lib/python3.8/dist-packages/MySQLdb/__init__.py", line 123, in Connect, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/register
[Wed Mar 23 16:00:18.006127 2022] [wsgi:error] [pid 3391:tid 139756465768192] [client 123.203.49.113:65033]     return Connection(*args, **kwargs), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/register
[Wed Mar 23 16:00:18.006134 2022] [wsgi:error] [pid 3391:tid 139756465768192] [client 123.203.49.113:65033]   File "/usr/local/lib/python3.8/dist-packages/MySQLdb/connections.py", line 185, in __init__, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/register
[Wed Mar 23 16:00:18.006138 2022] [wsgi:error] [pid 3391:tid 139756465768192] [client 123.203.49.113:65033]     super().__init__(*args, **kwargs2), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/register
[Wed Mar 23 16:00:18.006141 2022] [wsgi:error] [pid 3391:tid 139756465768192] [client 123.203.49.113:65033] MySQLdb._exceptions.OperationalError: (2002, "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)"), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/register
[Wed Mar 23 16:43:48.736045 2022] [wsgi:error] [pid 3888:tid 140241436317440] [client 123.203.49.113:58365] [2022-03-23 16:43:48,734] ERROR in app: Exception on /prod1 [GET]
[Wed Mar 23 16:43:48.736075 2022] [wsgi:error] [pid 3888:tid 140241436317440] [client 123.203.49.113:58365] Traceback (most recent call last):
[Wed Mar 23 16:43:48.736079 2022] [wsgi:error] [pid 3888:tid 140241436317440] [client 123.203.49.113:58365]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app
[Wed Mar 23 16:43:48.736083 2022] [wsgi:error] [pid 3888:tid 140241436317440] [client 123.203.49.113:58365]     response = self.full_dispatch_request()
[Wed Mar 23 16:43:48.736086 2022] [wsgi:error] [pid 3888:tid 140241436317440] [client 123.203.49.113:58365]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request
[Wed Mar 23 16:43:48.736090 2022] [wsgi:error] [pid 3888:tid 140241436317440] [client 123.203.49.113:58365]     rv = self.handle_user_exception(e)
[Wed Mar 23 16:43:48.736093 2022] [wsgi:error] [pid 3888:tid 140241436317440] [client 123.203.49.113:58365]   File "/usr/local/lib/python3.8/dist-packages/flask_restful/__init__.py", line 271, in error_router
[Wed Mar 23 16:43:48.736096 2022] [wsgi:error] [pid 3888:tid 140241436317440] [client 123.203.49.113:58365]     return original_handler(e)
[Wed Mar 23 16:43:48.736099 2022] [wsgi:error] [pid 3888:tid 140241436317440] [client 123.203.49.113:58365]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request
[Wed Mar 23 16:43:48.736102 2022] [wsgi:error] [pid 3888:tid 140241436317440] [client 123.203.49.113:58365]     rv = self.dispatch_request()
[Wed Mar 23 16:43:48.736105 2022] [wsgi:error] [pid 3888:tid 140241436317440] [client 123.203.49.113:58365]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request
[Wed Mar 23 16:43:48.736109 2022] [wsgi:error] [pid 3888:tid 140241436317440] [client 123.203.49.113:58365]     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
[Wed Mar 23 16:43:48.736112 2022] [wsgi:error] [pid 3888:tid 140241436317440] [client 123.203.49.113:58365]   File "/var/www/html/init.py", line 216, in prod
[Wed Mar 23 16:43:48.736115 2022] [wsgi:error] [pid 3888:tid 140241436317440] [client 123.203.49.113:58365]     return render_template('product_001.html')
[Wed Mar 23 16:43:48.736118 2022] [wsgi:error] [pid 3888:tid 140241436317440] [client 123.203.49.113:58365]   File "/usr/local/lib/python3.8/dist-packages/flask/templating.py", line 148, in render_template
[Wed Mar 23 16:43:48.736231 2022] [wsgi:error] [pid 3888:tid 140241436317440] [client 123.203.49.113:58365]     ctx.app.jinja_env.get_or_select_template(template_name_or_list),
[Wed Mar 23 16:43:48.736239 2022] [wsgi:error] [pid 3888:tid 140241436317440] [client 123.203.49.113:58365]   File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 1068, in get_or_select_template
[Wed Mar 23 16:43:48.736244 2022] [wsgi:error] [pid 3888:tid 140241436317440] [client 123.203.49.113:58365]     return self.get_template(template_name_or_list, parent, globals)
[Wed Mar 23 16:43:48.736262 2022] [wsgi:error] [pid 3888:tid 140241436317440] [client 123.203.49.113:58365]   File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 997, in get_template
[Wed Mar 23 16:43:48.736266 2022] [wsgi:error] [pid 3888:tid 140241436317440] [client 123.203.49.113:58365]     return self._load_template(name, globals)
[Wed Mar 23 16:43:48.736270 2022] [wsgi:error] [pid 3888:tid 140241436317440] [client 123.203.49.113:58365]   File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 958, in _load_template
[Wed Mar 23 16:43:48.736273 2022] [wsgi:error] [pid 3888:tid 140241436317440] [client 123.203.49.113:58365]     template = self.loader.load(self, name, self.make_globals(globals))
[Wed Mar 23 16:43:48.736276 2022] [wsgi:error] [pid 3888:tid 140241436317440] [client 123.203.49.113:58365]   File "/usr/local/lib/python3.8/dist-packages/jinja2/loaders.py", line 125, in load
[Wed Mar 23 16:43:48.736279 2022] [wsgi:error] [pid 3888:tid 140241436317440] [client 123.203.49.113:58365]     source, filename, uptodate = self.get_source(environment, name)
[Wed Mar 23 16:43:48.736282 2022] [wsgi:error] [pid 3888:tid 140241436317440] [client 123.203.49.113:58365]   File "/usr/local/lib/python3.8/dist-packages/flask/templating.py", line 59, in get_source
[Wed Mar 23 16:43:48.736285 2022] [wsgi:error] [pid 3888:tid 140241436317440] [client 123.203.49.113:58365]     return self._get_source_fast(environment, template)
[Wed Mar 23 16:43:48.736288 2022] [wsgi:error] [pid 3888:tid 140241436317440] [client 123.203.49.113:58365]   File "/usr/local/lib/python3.8/dist-packages/flask/templating.py", line 95, in _get_source_fast
[Wed Mar 23 16:43:48.736292 2022] [wsgi:error] [pid 3888:tid 140241436317440] [client 123.203.49.113:58365]     raise TemplateNotFound(template)
[Wed Mar 23 16:43:48.736294 2022] [wsgi:error] [pid 3888:tid 140241436317440] [client 123.203.49.113:58365] jinja2.exceptions.TemplateNotFound: product_001.html
[Wed Mar 23 16:43:56.024399 2022] [wsgi:error] [pid 3978:tid 140090189756160] [client 123.203.49.113:58368] [2022-03-23 16:43:56,022] ERROR in app: Exception on /prod1 [GET]
[Wed Mar 23 16:43:56.024438 2022] [wsgi:error] [pid 3978:tid 140090189756160] [client 123.203.49.113:58368] Traceback (most recent call last):
[Wed Mar 23 16:43:56.024442 2022] [wsgi:error] [pid 3978:tid 140090189756160] [client 123.203.49.113:58368]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app
[Wed Mar 23 16:43:56.024445 2022] [wsgi:error] [pid 3978:tid 140090189756160] [client 123.203.49.113:58368]     response = self.full_dispatch_request()
[Wed Mar 23 16:43:56.024449 2022] [wsgi:error] [pid 3978:tid 140090189756160] [client 123.203.49.113:58368]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request
[Wed Mar 23 16:43:56.024452 2022] [wsgi:error] [pid 3978:tid 140090189756160] [client 123.203.49.113:58368]     rv = self.handle_user_exception(e)
[Wed Mar 23 16:43:56.024455 2022] [wsgi:error] [pid 3978:tid 140090189756160] [client 123.203.49.113:58368]   File "/usr/local/lib/python3.8/dist-packages/flask_restful/__init__.py", line 271, in error_router
[Wed Mar 23 16:43:56.024459 2022] [wsgi:error] [pid 3978:tid 140090189756160] [client 123.203.49.113:58368]     return original_handler(e)
[Wed Mar 23 16:43:56.024462 2022] [wsgi:error] [pid 3978:tid 140090189756160] [client 123.203.49.113:58368]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request
[Wed Mar 23 16:43:56.024465 2022] [wsgi:error] [pid 3978:tid 140090189756160] [client 123.203.49.113:58368]     rv = self.dispatch_request()
[Wed Mar 23 16:43:56.024468 2022] [wsgi:error] [pid 3978:tid 140090189756160] [client 123.203.49.113:58368]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request
[Wed Mar 23 16:43:56.024471 2022] [wsgi:error] [pid 3978:tid 140090189756160] [client 123.203.49.113:58368]     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
[Wed Mar 23 16:43:56.024481 2022] [wsgi:error] [pid 3978:tid 140090189756160] [client 123.203.49.113:58368]   File "/var/www/html/init.py", line 216, in prod
[Wed Mar 23 16:43:56.024484 2022] [wsgi:error] [pid 3978:tid 140090189756160] [client 123.203.49.113:58368]     return render_template('product_001.html')
[Wed Mar 23 16:43:56.024487 2022] [wsgi:error] [pid 3978:tid 140090189756160] [client 123.203.49.113:58368]   File "/usr/local/lib/python3.8/dist-packages/flask/templating.py", line 148, in render_template
[Wed Mar 23 16:43:56.024491 2022] [wsgi:error] [pid 3978:tid 140090189756160] [client 123.203.49.113:58368]     ctx.app.jinja_env.get_or_select_template(template_name_or_list),
[Wed Mar 23 16:43:56.024494 2022] [wsgi:error] [pid 3978:tid 140090189756160] [client 123.203.49.113:58368]   File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 1068, in get_or_select_template
[Wed Mar 23 16:43:56.024497 2022] [wsgi:error] [pid 3978:tid 140090189756160] [client 123.203.49.113:58368]     return self.get_template(template_name_or_list, parent, globals)
[Wed Mar 23 16:43:56.024512 2022] [wsgi:error] [pid 3978:tid 140090189756160] [client 123.203.49.113:58368]   File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 997, in get_template
[Wed Mar 23 16:43:56.024515 2022] [wsgi:error] [pid 3978:tid 140090189756160] [client 123.203.49.113:58368]     return self._load_template(name, globals)
[Wed Mar 23 16:43:56.024518 2022] [wsgi:error] [pid 3978:tid 140090189756160] [client 123.203.49.113:58368]   File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 958, in _load_template
[Wed Mar 23 16:43:56.024521 2022] [wsgi:error] [pid 3978:tid 140090189756160] [client 123.203.49.113:58368]     template = self.loader.load(self, name, self.make_globals(globals))
[Wed Mar 23 16:43:56.024524 2022] [wsgi:error] [pid 3978:tid 140090189756160] [client 123.203.49.113:58368]   File "/usr/local/lib/python3.8/dist-packages/jinja2/loaders.py", line 125, in load
[Wed Mar 23 16:43:56.024527 2022] [wsgi:error] [pid 3978:tid 140090189756160] [client 123.203.49.113:58368]     source, filename, uptodate = self.get_source(environment, name)
[Wed Mar 23 16:43:56.024530 2022] [wsgi:error] [pid 3978:tid 140090189756160] [client 123.203.49.113:58368]   File "/usr/local/lib/python3.8/dist-packages/flask/templating.py", line 59, in get_source
[Wed Mar 23 16:43:56.024533 2022] [wsgi:error] [pid 3978:tid 140090189756160] [client 123.203.49.113:58368]     return self._get_source_fast(environment, template)
[Wed Mar 23 16:43:56.024535 2022] [wsgi:error] [pid 3978:tid 140090189756160] [client 123.203.49.113:58368]   File "/usr/local/lib/python3.8/dist-packages/flask/templating.py", line 95, in _get_source_fast
[Wed Mar 23 16:43:56.024538 2022] [wsgi:error] [pid 3978:tid 140090189756160] [client 123.203.49.113:58368]     raise TemplateNotFound(template)
[Wed Mar 23 16:43:56.024541 2022] [wsgi:error] [pid 3978:tid 140090189756160] [client 123.203.49.113:58368] jinja2.exceptions.TemplateNotFound: product_001.html
[Thu Mar 24 03:19:06.547022 2022] [wsgi:error] [pid 6452:tid 139628447201024] [client 123.203.49.113:53221] [2022-03-24 03:19:06,543] ERROR in app: Exception on /register [POST], referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/register
[Thu Mar 24 03:19:06.547633 2022] [wsgi:error] [pid 6452:tid 139628447201024] [client 123.203.49.113:53221] Traceback (most recent call last):, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/register
[Thu Mar 24 03:19:06.547638 2022] [wsgi:error] [pid 6452:tid 139628447201024] [client 123.203.49.113:53221]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/register
[Thu Mar 24 03:19:06.547642 2022] [wsgi:error] [pid 6452:tid 139628447201024] [client 123.203.49.113:53221]     response = self.full_dispatch_request(), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/register
[Thu Mar 24 03:19:06.547650 2022] [wsgi:error] [pid 6452:tid 139628447201024] [client 123.203.49.113:53221]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/register
[Thu Mar 24 03:19:06.547654 2022] [wsgi:error] [pid 6452:tid 139628447201024] [client 123.203.49.113:53221]     rv = self.handle_user_exception(e), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/register
[Thu Mar 24 03:19:06.547657 2022] [wsgi:error] [pid 6452:tid 139628447201024] [client 123.203.49.113:53221]   File "/usr/local/lib/python3.8/dist-packages/flask_restful/__init__.py", line 271, in error_router, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/register
[Thu Mar 24 03:19:06.547660 2022] [wsgi:error] [pid 6452:tid 139628447201024] [client 123.203.49.113:53221]     return original_handler(e), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/register
[Thu Mar 24 03:19:06.547663 2022] [wsgi:error] [pid 6452:tid 139628447201024] [client 123.203.49.113:53221]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/register
[Thu Mar 24 03:19:06.547666 2022] [wsgi:error] [pid 6452:tid 139628447201024] [client 123.203.49.113:53221]     rv = self.dispatch_request(), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/register
[Thu Mar 24 03:19:06.547669 2022] [wsgi:error] [pid 6452:tid 139628447201024] [client 123.203.49.113:53221]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/register
[Thu Mar 24 03:19:06.547673 2022] [wsgi:error] [pid 6452:tid 139628447201024] [client 123.203.49.113:53221]     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/register
[Thu Mar 24 03:19:06.547676 2022] [wsgi:error] [pid 6452:tid 139628447201024] [client 123.203.49.113:53221]   File "/var/www/html/init.py", line 51, in register, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/register
[Thu Mar 24 03:19:06.547679 2022] [wsgi:error] [pid 6452:tid 139628447201024] [client 123.203.49.113:53221]     cur = mysql.connection.cursor(), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/register
[Thu Mar 24 03:19:06.547682 2022] [wsgi:error] [pid 6452:tid 139628447201024] [client 123.203.49.113:53221]   File "/usr/local/lib/python3.8/dist-packages/flask_mysqldb/__init__.py", line 101, in connection, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/register
[Thu Mar 24 03:19:06.547685 2022] [wsgi:error] [pid 6452:tid 139628447201024] [client 123.203.49.113:53221]     ctx.mysql_db = self.connect, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/register
[Thu Mar 24 03:19:06.547688 2022] [wsgi:error] [pid 6452:tid 139628447201024] [client 123.203.49.113:53221]   File "/usr/local/lib/python3.8/dist-packages/flask_mysqldb/__init__.py", line 88, in connect, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/register
[Thu Mar 24 03:19:06.547691 2022] [wsgi:error] [pid 6452:tid 139628447201024] [client 123.203.49.113:53221]     return MySQLdb.connect(**kwargs), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/register
[Thu Mar 24 03:19:06.547694 2022] [wsgi:error] [pid 6452:tid 139628447201024] [client 123.203.49.113:53221]   File "/usr/local/lib/python3.8/dist-packages/MySQLdb/__init__.py", line 123, in Connect, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/register
[Thu Mar 24 03:19:06.547697 2022] [wsgi:error] [pid 6452:tid 139628447201024] [client 123.203.49.113:53221]     return Connection(*args, **kwargs), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/register
[Thu Mar 24 03:19:06.547700 2022] [wsgi:error] [pid 6452:tid 139628447201024] [client 123.203.49.113:53221]   File "/usr/local/lib/python3.8/dist-packages/MySQLdb/connections.py", line 185, in __init__, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/register
[Thu Mar 24 03:19:06.547706 2022] [wsgi:error] [pid 6452:tid 139628447201024] [client 123.203.49.113:53221]     super().__init__(*args, **kwargs2), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/register
[Thu Mar 24 03:19:06.547710 2022] [wsgi:error] [pid 6452:tid 139628447201024] [client 123.203.49.113:53221] MySQLdb._exceptions.OperationalError: (2002, "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)"), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/register
[Thu Mar 24 19:47:18.925386 2022] [wsgi:error] [pid 23084:tid 140157147617024] [client 123.203.49.113:57101] [2022-03-24 19:47:18,920] ERROR in app: Exception on /cart [POST], referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:47:18.926304 2022] [wsgi:error] [pid 23084:tid 140157147617024] [client 123.203.49.113:57101] Traceback (most recent call last):, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:47:18.926311 2022] [wsgi:error] [pid 23084:tid 140157147617024] [client 123.203.49.113:57101]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:47:18.926315 2022] [wsgi:error] [pid 23084:tid 140157147617024] [client 123.203.49.113:57101]     response = self.full_dispatch_request(), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:47:18.926318 2022] [wsgi:error] [pid 23084:tid 140157147617024] [client 123.203.49.113:57101]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:47:18.926322 2022] [wsgi:error] [pid 23084:tid 140157147617024] [client 123.203.49.113:57101]     rv = self.handle_user_exception(e), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:47:18.926325 2022] [wsgi:error] [pid 23084:tid 140157147617024] [client 123.203.49.113:57101]   File "/usr/local/lib/python3.8/dist-packages/flask_restful/__init__.py", line 271, in error_router, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:47:18.926328 2022] [wsgi:error] [pid 23084:tid 140157147617024] [client 123.203.49.113:57101]     return original_handler(e), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:47:18.926331 2022] [wsgi:error] [pid 23084:tid 140157147617024] [client 123.203.49.113:57101]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:47:18.926335 2022] [wsgi:error] [pid 23084:tid 140157147617024] [client 123.203.49.113:57101]     rv = self.dispatch_request(), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:47:18.926338 2022] [wsgi:error] [pid 23084:tid 140157147617024] [client 123.203.49.113:57101]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:47:18.926341 2022] [wsgi:error] [pid 23084:tid 140157147617024] [client 123.203.49.113:57101]     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:47:18.926344 2022] [wsgi:error] [pid 23084:tid 140157147617024] [client 123.203.49.113:57101]   File "/var/www/html/init.py", line 162, in cart, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:47:18.926347 2022] [wsgi:error] [pid 23084:tid 140157147617024] [client 123.203.49.113:57101]     cur = mysql.connection.cursor(), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:47:18.926356 2022] [wsgi:error] [pid 23084:tid 140157147617024] [client 123.203.49.113:57101]   File "/usr/local/lib/python3.8/dist-packages/flask_mysqldb/__init__.py", line 101, in connection, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:47:18.926359 2022] [wsgi:error] [pid 23084:tid 140157147617024] [client 123.203.49.113:57101]     ctx.mysql_db = self.connect, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:47:18.926362 2022] [wsgi:error] [pid 23084:tid 140157147617024] [client 123.203.49.113:57101]   File "/usr/local/lib/python3.8/dist-packages/flask_mysqldb/__init__.py", line 88, in connect, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:47:18.926365 2022] [wsgi:error] [pid 23084:tid 140157147617024] [client 123.203.49.113:57101]     return MySQLdb.connect(**kwargs), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:47:18.926368 2022] [wsgi:error] [pid 23084:tid 140157147617024] [client 123.203.49.113:57101]   File "/usr/local/lib/python3.8/dist-packages/MySQLdb/__init__.py", line 123, in Connect, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:47:18.926371 2022] [wsgi:error] [pid 23084:tid 140157147617024] [client 123.203.49.113:57101]     return Connection(*args, **kwargs), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:47:18.926374 2022] [wsgi:error] [pid 23084:tid 140157147617024] [client 123.203.49.113:57101]   File "/usr/local/lib/python3.8/dist-packages/MySQLdb/connections.py", line 185, in __init__, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:47:18.926377 2022] [wsgi:error] [pid 23084:tid 140157147617024] [client 123.203.49.113:57101]     super().__init__(*args, **kwargs2), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:47:18.926381 2022] [wsgi:error] [pid 23084:tid 140157147617024] [client 123.203.49.113:57101] MySQLdb._exceptions.OperationalError: (2002, "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)"), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:19.145407 2022] [wsgi:error] [pid 23207:tid 139887923672832] [client 123.203.49.113:57107] [2022-03-24 19:48:19,144] ERROR in app: Exception on /cart [POST], referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:19.145442 2022] [wsgi:error] [pid 23207:tid 139887923672832] [client 123.203.49.113:57107] Traceback (most recent call last):, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:19.145446 2022] [wsgi:error] [pid 23207:tid 139887923672832] [client 123.203.49.113:57107]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:19.145450 2022] [wsgi:error] [pid 23207:tid 139887923672832] [client 123.203.49.113:57107]     response = self.full_dispatch_request(), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:19.145454 2022] [wsgi:error] [pid 23207:tid 139887923672832] [client 123.203.49.113:57107]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:19.145457 2022] [wsgi:error] [pid 23207:tid 139887923672832] [client 123.203.49.113:57107]     rv = self.handle_user_exception(e), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:19.145461 2022] [wsgi:error] [pid 23207:tid 139887923672832] [client 123.203.49.113:57107]   File "/usr/local/lib/python3.8/dist-packages/flask_restful/__init__.py", line 271, in error_router, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:19.145471 2022] [wsgi:error] [pid 23207:tid 139887923672832] [client 123.203.49.113:57107]     return original_handler(e), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:19.145475 2022] [wsgi:error] [pid 23207:tid 139887923672832] [client 123.203.49.113:57107]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:19.145478 2022] [wsgi:error] [pid 23207:tid 139887923672832] [client 123.203.49.113:57107]     rv = self.dispatch_request(), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:19.145481 2022] [wsgi:error] [pid 23207:tid 139887923672832] [client 123.203.49.113:57107]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:19.145484 2022] [wsgi:error] [pid 23207:tid 139887923672832] [client 123.203.49.113:57107]     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:19.145487 2022] [wsgi:error] [pid 23207:tid 139887923672832] [client 123.203.49.113:57107]   File "/var/www/html/init.py", line 162, in cart, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:19.145491 2022] [wsgi:error] [pid 23207:tid 139887923672832] [client 123.203.49.113:57107]     cur = mysql.connection.cursor(), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:19.145494 2022] [wsgi:error] [pid 23207:tid 139887923672832] [client 123.203.49.113:57107]   File "/usr/local/lib/python3.8/dist-packages/flask_mysqldb/__init__.py", line 101, in connection, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:19.145497 2022] [wsgi:error] [pid 23207:tid 139887923672832] [client 123.203.49.113:57107]     ctx.mysql_db = self.connect, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:19.145500 2022] [wsgi:error] [pid 23207:tid 139887923672832] [client 123.203.49.113:57107]   File "/usr/local/lib/python3.8/dist-packages/flask_mysqldb/__init__.py", line 88, in connect, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:19.145503 2022] [wsgi:error] [pid 23207:tid 139887923672832] [client 123.203.49.113:57107]     return MySQLdb.connect(**kwargs), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:19.145506 2022] [wsgi:error] [pid 23207:tid 139887923672832] [client 123.203.49.113:57107]   File "/usr/local/lib/python3.8/dist-packages/MySQLdb/__init__.py", line 123, in Connect, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:19.145510 2022] [wsgi:error] [pid 23207:tid 139887923672832] [client 123.203.49.113:57107]     return Connection(*args, **kwargs), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:19.145513 2022] [wsgi:error] [pid 23207:tid 139887923672832] [client 123.203.49.113:57107]   File "/usr/local/lib/python3.8/dist-packages/MySQLdb/connections.py", line 185, in __init__, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:19.145516 2022] [wsgi:error] [pid 23207:tid 139887923672832] [client 123.203.49.113:57107]     super().__init__(*args, **kwargs2), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:19.145519 2022] [wsgi:error] [pid 23207:tid 139887923672832] [client 123.203.49.113:57107] MySQLdb._exceptions.OperationalError: (2003, "Can't connect to MySQL server on '127.0.0.1:3306' (111)"), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:50.244202 2022] [wsgi:error] [pid 23281:tid 139684375500544] [client 123.203.49.113:57109] [2022-03-24 19:48:50,243] ERROR in app: Exception on /cart [POST], referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:50.244247 2022] [wsgi:error] [pid 23281:tid 139684375500544] [client 123.203.49.113:57109] Traceback (most recent call last):, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:50.244251 2022] [wsgi:error] [pid 23281:tid 139684375500544] [client 123.203.49.113:57109]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:50.244255 2022] [wsgi:error] [pid 23281:tid 139684375500544] [client 123.203.49.113:57109]     response = self.full_dispatch_request(), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:50.244258 2022] [wsgi:error] [pid 23281:tid 139684375500544] [client 123.203.49.113:57109]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:50.244261 2022] [wsgi:error] [pid 23281:tid 139684375500544] [client 123.203.49.113:57109]     rv = self.handle_user_exception(e), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:50.244265 2022] [wsgi:error] [pid 23281:tid 139684375500544] [client 123.203.49.113:57109]   File "/usr/local/lib/python3.8/dist-packages/flask_restful/__init__.py", line 271, in error_router, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:50.244268 2022] [wsgi:error] [pid 23281:tid 139684375500544] [client 123.203.49.113:57109]     return original_handler(e), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:50.244271 2022] [wsgi:error] [pid 23281:tid 139684375500544] [client 123.203.49.113:57109]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:50.244274 2022] [wsgi:error] [pid 23281:tid 139684375500544] [client 123.203.49.113:57109]     rv = self.dispatch_request(), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:50.244277 2022] [wsgi:error] [pid 23281:tid 139684375500544] [client 123.203.49.113:57109]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:50.244281 2022] [wsgi:error] [pid 23281:tid 139684375500544] [client 123.203.49.113:57109]     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:50.244284 2022] [wsgi:error] [pid 23281:tid 139684375500544] [client 123.203.49.113:57109]   File "/var/www/html/init.py", line 162, in cart, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:50.244287 2022] [wsgi:error] [pid 23281:tid 139684375500544] [client 123.203.49.113:57109]     cur = mysql.connection.cursor(), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:50.244290 2022] [wsgi:error] [pid 23281:tid 139684375500544] [client 123.203.49.113:57109]   File "/usr/local/lib/python3.8/dist-packages/flask_mysqldb/__init__.py", line 101, in connection, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:50.244293 2022] [wsgi:error] [pid 23281:tid 139684375500544] [client 123.203.49.113:57109]     ctx.mysql_db = self.connect, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:50.244296 2022] [wsgi:error] [pid 23281:tid 139684375500544] [client 123.203.49.113:57109]   File "/usr/local/lib/python3.8/dist-packages/flask_mysqldb/__init__.py", line 88, in connect, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:50.244299 2022] [wsgi:error] [pid 23281:tid 139684375500544] [client 123.203.49.113:57109]     return MySQLdb.connect(**kwargs), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:50.244305 2022] [wsgi:error] [pid 23281:tid 139684375500544] [client 123.203.49.113:57109]   File "/usr/local/lib/python3.8/dist-packages/MySQLdb/__init__.py", line 123, in Connect, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:50.244309 2022] [wsgi:error] [pid 23281:tid 139684375500544] [client 123.203.49.113:57109]     return Connection(*args, **kwargs), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:50.244312 2022] [wsgi:error] [pid 23281:tid 139684375500544] [client 123.203.49.113:57109]   File "/usr/local/lib/python3.8/dist-packages/MySQLdb/connections.py", line 185, in __init__, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:50.244315 2022] [wsgi:error] [pid 23281:tid 139684375500544] [client 123.203.49.113:57109]     super().__init__(*args, **kwargs2), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:50.244318 2022] [wsgi:error] [pid 23281:tid 139684375500544] [client 123.203.49.113:57109] MySQLdb._exceptions.OperationalError: (2005, "Unknown MySQL server host 'db' (-3)"), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:54.007760 2022] [wsgi:error] [pid 23281:tid 139684358715136] [client 123.203.49.113:57110] [2022-03-24 19:48:54,007] ERROR in app: Exception on /cart [POST], referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:54.007787 2022] [wsgi:error] [pid 23281:tid 139684358715136] [client 123.203.49.113:57110] Traceback (most recent call last):, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:54.007791 2022] [wsgi:error] [pid 23281:tid 139684358715136] [client 123.203.49.113:57110]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:54.007795 2022] [wsgi:error] [pid 23281:tid 139684358715136] [client 123.203.49.113:57110]     response = self.full_dispatch_request(), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:54.007798 2022] [wsgi:error] [pid 23281:tid 139684358715136] [client 123.203.49.113:57110]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:54.007802 2022] [wsgi:error] [pid 23281:tid 139684358715136] [client 123.203.49.113:57110]     rv = self.handle_user_exception(e), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:54.007805 2022] [wsgi:error] [pid 23281:tid 139684358715136] [client 123.203.49.113:57110]   File "/usr/local/lib/python3.8/dist-packages/flask_restful/__init__.py", line 271, in error_router, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:54.007808 2022] [wsgi:error] [pid 23281:tid 139684358715136] [client 123.203.49.113:57110]     return original_handler(e), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:54.007811 2022] [wsgi:error] [pid 23281:tid 139684358715136] [client 123.203.49.113:57110]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:54.007814 2022] [wsgi:error] [pid 23281:tid 139684358715136] [client 123.203.49.113:57110]     rv = self.dispatch_request(), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:54.007817 2022] [wsgi:error] [pid 23281:tid 139684358715136] [client 123.203.49.113:57110]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:54.007828 2022] [wsgi:error] [pid 23281:tid 139684358715136] [client 123.203.49.113:57110]     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:54.007831 2022] [wsgi:error] [pid 23281:tid 139684358715136] [client 123.203.49.113:57110]   File "/var/www/html/init.py", line 162, in cart, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:54.007834 2022] [wsgi:error] [pid 23281:tid 139684358715136] [client 123.203.49.113:57110]     cur = mysql.connection.cursor(), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:54.007837 2022] [wsgi:error] [pid 23281:tid 139684358715136] [client 123.203.49.113:57110]   File "/usr/local/lib/python3.8/dist-packages/flask_mysqldb/__init__.py", line 101, in connection, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:54.007840 2022] [wsgi:error] [pid 23281:tid 139684358715136] [client 123.203.49.113:57110]     ctx.mysql_db = self.connect, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:54.007843 2022] [wsgi:error] [pid 23281:tid 139684358715136] [client 123.203.49.113:57110]   File "/usr/local/lib/python3.8/dist-packages/flask_mysqldb/__init__.py", line 88, in connect, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:54.007846 2022] [wsgi:error] [pid 23281:tid 139684358715136] [client 123.203.49.113:57110]     return MySQLdb.connect(**kwargs), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:54.007849 2022] [wsgi:error] [pid 23281:tid 139684358715136] [client 123.203.49.113:57110]   File "/usr/local/lib/python3.8/dist-packages/MySQLdb/__init__.py", line 123, in Connect, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:54.007852 2022] [wsgi:error] [pid 23281:tid 139684358715136] [client 123.203.49.113:57110]     return Connection(*args, **kwargs), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:54.007855 2022] [wsgi:error] [pid 23281:tid 139684358715136] [client 123.203.49.113:57110]   File "/usr/local/lib/python3.8/dist-packages/MySQLdb/connections.py", line 185, in __init__, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:54.007858 2022] [wsgi:error] [pid 23281:tid 139684358715136] [client 123.203.49.113:57110]     super().__init__(*args, **kwargs2), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:54.007861 2022] [wsgi:error] [pid 23281:tid 139684358715136] [client 123.203.49.113:57110] MySQLdb._exceptions.OperationalError: (2005, "Unknown MySQL server host 'db' (-3)"), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:58.610267 2022] [wsgi:error] [pid 23282:tid 139684281841408] [client 123.203.49.113:57112] [2022-03-24 19:48:58,609] ERROR in app: Exception on /cart [POST], referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:58.610301 2022] [wsgi:error] [pid 23282:tid 139684281841408] [client 123.203.49.113:57112] Traceback (most recent call last):, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:58.610305 2022] [wsgi:error] [pid 23282:tid 139684281841408] [client 123.203.49.113:57112]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:58.610310 2022] [wsgi:error] [pid 23282:tid 139684281841408] [client 123.203.49.113:57112]     response = self.full_dispatch_request(), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:58.610313 2022] [wsgi:error] [pid 23282:tid 139684281841408] [client 123.203.49.113:57112]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:58.610325 2022] [wsgi:error] [pid 23282:tid 139684281841408] [client 123.203.49.113:57112]     rv = self.handle_user_exception(e), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:58.610329 2022] [wsgi:error] [pid 23282:tid 139684281841408] [client 123.203.49.113:57112]   File "/usr/local/lib/python3.8/dist-packages/flask_restful/__init__.py", line 271, in error_router, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:58.610332 2022] [wsgi:error] [pid 23282:tid 139684281841408] [client 123.203.49.113:57112]     return original_handler(e), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:58.610335 2022] [wsgi:error] [pid 23282:tid 139684281841408] [client 123.203.49.113:57112]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:58.610339 2022] [wsgi:error] [pid 23282:tid 139684281841408] [client 123.203.49.113:57112]     rv = self.dispatch_request(), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:58.610342 2022] [wsgi:error] [pid 23282:tid 139684281841408] [client 123.203.49.113:57112]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:58.610345 2022] [wsgi:error] [pid 23282:tid 139684281841408] [client 123.203.49.113:57112]     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:58.610348 2022] [wsgi:error] [pid 23282:tid 139684281841408] [client 123.203.49.113:57112]   File "/var/www/html/init.py", line 162, in cart, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:58.610352 2022] [wsgi:error] [pid 23282:tid 139684281841408] [client 123.203.49.113:57112]     cur = mysql.connection.cursor(), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:58.610355 2022] [wsgi:error] [pid 23282:tid 139684281841408] [client 123.203.49.113:57112]   File "/usr/local/lib/python3.8/dist-packages/flask_mysqldb/__init__.py", line 101, in connection, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:58.610358 2022] [wsgi:error] [pid 23282:tid 139684281841408] [client 123.203.49.113:57112]     ctx.mysql_db = self.connect, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:58.610361 2022] [wsgi:error] [pid 23282:tid 139684281841408] [client 123.203.49.113:57112]   File "/usr/local/lib/python3.8/dist-packages/flask_mysqldb/__init__.py", line 88, in connect, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:58.610365 2022] [wsgi:error] [pid 23282:tid 139684281841408] [client 123.203.49.113:57112]     return MySQLdb.connect(**kwargs), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:58.610368 2022] [wsgi:error] [pid 23282:tid 139684281841408] [client 123.203.49.113:57112]   File "/usr/local/lib/python3.8/dist-packages/MySQLdb/__init__.py", line 123, in Connect, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:58.610371 2022] [wsgi:error] [pid 23282:tid 139684281841408] [client 123.203.49.113:57112]     return Connection(*args, **kwargs), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:58.610374 2022] [wsgi:error] [pid 23282:tid 139684281841408] [client 123.203.49.113:57112]   File "/usr/local/lib/python3.8/dist-packages/MySQLdb/connections.py", line 185, in __init__, referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:58.610377 2022] [wsgi:error] [pid 23282:tid 139684281841408] [client 123.203.49.113:57112]     super().__init__(*args, **kwargs2), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:48:58.610383 2022] [wsgi:error] [pid 23282:tid 139684281841408] [client 123.203.49.113:57112] MySQLdb._exceptions.OperationalError: (2005, "Unknown MySQL server host 'db' (-3)"), referer: http://ec2-18-162-111-72.ap-east-1.compute.amazonaws.com/cart
[Thu Mar 24 19:52:06.492266 2022] [wsgi:error] [pid 23359:tid 140700561692416] [client 123.203.49.113:57123] [2022-03-24 19:52:06,491] ERROR in app: Exception on /checkout [GET]
[Thu Mar 24 19:52:06.492304 2022] [wsgi:error] [pid 23359:tid 140700561692416] [client 123.203.49.113:57123] Traceback (most recent call last):
[Thu Mar 24 19:52:06.492308 2022] [wsgi:error] [pid 23359:tid 140700561692416] [client 123.203.49.113:57123]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app
[Thu Mar 24 19:52:06.492312 2022] [wsgi:error] [pid 23359:tid 140700561692416] [client 123.203.49.113:57123]     response = self.full_dispatch_request()
[Thu Mar 24 19:52:06.492315 2022] [wsgi:error] [pid 23359:tid 140700561692416] [client 123.203.49.113:57123]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request
[Thu Mar 24 19:52:06.492318 2022] [wsgi:error] [pid 23359:tid 140700561692416] [client 123.203.49.113:57123]     rv = self.handle_user_exception(e)
[Thu Mar 24 19:52:06.492321 2022] [wsgi:error] [pid 23359:tid 140700561692416] [client 123.203.49.113:57123]   File "/usr/local/lib/python3.8/dist-packages/flask_restful/__init__.py", line 271, in error_router
[Thu Mar 24 19:52:06.492325 2022] [wsgi:error] [pid 23359:tid 140700561692416] [client 123.203.49.113:57123]     return original_handler(e)
[Thu Mar 24 19:52:06.492328 2022] [wsgi:error] [pid 23359:tid 140700561692416] [client 123.203.49.113:57123]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request
[Thu Mar 24 19:52:06.492331 2022] [wsgi:error] [pid 23359:tid 140700561692416] [client 123.203.49.113:57123]     rv = self.dispatch_request()
[Thu Mar 24 19:52:06.492334 2022] [wsgi:error] [pid 23359:tid 140700561692416] [client 123.203.49.113:57123]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request
[Thu Mar 24 19:52:06.492337 2022] [wsgi:error] [pid 23359:tid 140700561692416] [client 123.203.49.113:57123]     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
[Thu Mar 24 19:52:06.492340 2022] [wsgi:error] [pid 23359:tid 140700561692416] [client 123.203.49.113:57123]   File "/var/www/html/init.py", line 176, in checkout
[Thu Mar 24 19:52:06.492343 2022] [wsgi:error] [pid 23359:tid 140700561692416] [client 123.203.49.113:57123]     cur = mysql.connection.cursor()
[Thu Mar 24 19:52:06.492346 2022] [wsgi:error] [pid 23359:tid 140700561692416] [client 123.203.49.113:57123]   File "/usr/local/lib/python3.8/dist-packages/flask_mysqldb/__init__.py", line 101, in connection
[Thu Mar 24 19:52:06.492349 2022] [wsgi:error] [pid 23359:tid 140700561692416] [client 123.203.49.113:57123]     ctx.mysql_db = self.connect
[Thu Mar 24 19:52:06.492352 2022] [wsgi:error] [pid 23359:tid 140700561692416] [client 123.203.49.113:57123]   File "/usr/local/lib/python3.8/dist-packages/flask_mysqldb/__init__.py", line 88, in connect
[Thu Mar 24 19:52:06.492355 2022] [wsgi:error] [pid 23359:tid 140700561692416] [client 123.203.49.113:57123]     return MySQLdb.connect(**kwargs)
[Thu Mar 24 19:52:06.492358 2022] [wsgi:error] [pid 23359:tid 140700561692416] [client 123.203.49.113:57123]   File "/usr/local/lib/python3.8/dist-packages/MySQLdb/__init__.py", line 123, in Connect
[Thu Mar 24 19:52:06.492361 2022] [wsgi:error] [pid 23359:tid 140700561692416] [client 123.203.49.113:57123]     return Connection(*args, **kwargs)
[Thu Mar 24 19:52:06.492364 2022] [wsgi:error] [pid 23359:tid 140700561692416] [client 123.203.49.113:57123]   File "/usr/local/lib/python3.8/dist-packages/MySQLdb/connections.py", line 185, in __init__
[Thu Mar 24 19:52:06.492374 2022] [wsgi:error] [pid 23359:tid 140700561692416] [client 123.203.49.113:57123]     super().__init__(*args, **kwargs2)
[Thu Mar 24 19:52:06.492377 2022] [wsgi:error] [pid 23359:tid 140700561692416] [client 123.203.49.113:57123] MySQLdb._exceptions.OperationalError: (2002, "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)")
[Thu Mar 24 19:53:05.176972 2022] [wsgi:error] [pid 23432:tid 139778513557248] [client 123.203.49.113:57124] [2022-03-24 19:53:05,173] ERROR in app: Exception on /checkout [GET]
[Thu Mar 24 19:53:05.177003 2022] [wsgi:error] [pid 23432:tid 139778513557248] [client 123.203.49.113:57124] Traceback (most recent call last):
[Thu Mar 24 19:53:05.177007 2022] [wsgi:error] [pid 23432:tid 139778513557248] [client 123.203.49.113:57124]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app
[Thu Mar 24 19:53:05.177011 2022] [wsgi:error] [pid 23432:tid 139778513557248] [client 123.203.49.113:57124]     response = self.full_dispatch_request()
[Thu Mar 24 19:53:05.177014 2022] [wsgi:error] [pid 23432:tid 139778513557248] [client 123.203.49.113:57124]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request
[Thu Mar 24 19:53:05.177017 2022] [wsgi:error] [pid 23432:tid 139778513557248] [client 123.203.49.113:57124]     rv = self.handle_user_exception(e)
[Thu Mar 24 19:53:05.177032 2022] [wsgi:error] [pid 23432:tid 139778513557248] [client 123.203.49.113:57124]   File "/usr/local/lib/python3.8/dist-packages/flask_restful/__init__.py", line 271, in error_router
[Thu Mar 24 19:53:05.177035 2022] [wsgi:error] [pid 23432:tid 139778513557248] [client 123.203.49.113:57124]     return original_handler(e)
[Thu Mar 24 19:53:05.177038 2022] [wsgi:error] [pid 23432:tid 139778513557248] [client 123.203.49.113:57124]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request
[Thu Mar 24 19:53:05.177041 2022] [wsgi:error] [pid 23432:tid 139778513557248] [client 123.203.49.113:57124]     rv = self.dispatch_request()
[Thu Mar 24 19:53:05.177044 2022] [wsgi:error] [pid 23432:tid 139778513557248] [client 123.203.49.113:57124]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request
[Thu Mar 24 19:53:05.177047 2022] [wsgi:error] [pid 23432:tid 139778513557248] [client 123.203.49.113:57124]     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
[Thu Mar 24 19:53:05.177050 2022] [wsgi:error] [pid 23432:tid 139778513557248] [client 123.203.49.113:57124]   File "/var/www/html/init.py", line 180, in checkout
[Thu Mar 24 19:53:05.177053 2022] [wsgi:error] [pid 23432:tid 139778513557248] [client 123.203.49.113:57124]     return render_template('checkout.html', )
[Thu Mar 24 19:53:05.177056 2022] [wsgi:error] [pid 23432:tid 139778513557248] [client 123.203.49.113:57124]   File "/usr/local/lib/python3.8/dist-packages/flask/templating.py", line 147, in render_template
[Thu Mar 24 19:53:05.177059 2022] [wsgi:error] [pid 23432:tid 139778513557248] [client 123.203.49.113:57124]     return _render(
[Thu Mar 24 19:53:05.177079 2022] [wsgi:error] [pid 23432:tid 139778513557248] [client 123.203.49.113:57124]   File "/usr/local/lib/python3.8/dist-packages/flask/templating.py", line 128, in _render
[Thu Mar 24 19:53:05.177082 2022] [wsgi:error] [pid 23432:tid 139778513557248] [client 123.203.49.113:57124]     rv = template.render(context)
[Thu Mar 24 19:53:05.177085 2022] [wsgi:error] [pid 23432:tid 139778513557248] [client 123.203.49.113:57124]   File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 1291, in render
[Thu Mar 24 19:53:05.177088 2022] [wsgi:error] [pid 23432:tid 139778513557248] [client 123.203.49.113:57124]     self.environment.handle_exception()
[Thu Mar 24 19:53:05.177091 2022] [wsgi:error] [pid 23432:tid 139778513557248] [client 123.203.49.113:57124]   File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 925, in handle_exception
[Thu Mar 24 19:53:05.177102 2022] [wsgi:error] [pid 23432:tid 139778513557248] [client 123.203.49.113:57124]     raise rewrite_traceback_stack(source=source)
[Thu Mar 24 19:53:05.177105 2022] [wsgi:error] [pid 23432:tid 139778513557248] [client 123.203.49.113:57124]   File "/var/www/html/templates/checkout.html", line 1, in top-level template code
[Thu Mar 24 19:53:05.177108 2022] [wsgi:error] [pid 23432:tid 139778513557248] [client 123.203.49.113:57124]     {% extends 'layout.html' %}
[Thu Mar 24 19:53:05.177111 2022] [wsgi:error] [pid 23432:tid 139778513557248] [client 123.203.49.113:57124]   File "/var/www/html/templates/layout.html", line 26, in top-level template code
[Thu Mar 24 19:53:05.177114 2022] [wsgi:error] [pid 23432:tid 139778513557248] [client 123.203.49.113:57124]     {% block body %}
[Thu Mar 24 19:53:05.177117 2022] [wsgi:error] [pid 23432:tid 139778513557248] [client 123.203.49.113:57124]   File "/var/www/html/templates/checkout.html", line 18, in block 'body'
[Thu Mar 24 19:53:05.177120 2022] [wsgi:error] [pid 23432:tid 139778513557248] [client 123.203.49.113:57124]     <h3 style="font-family: Roboto, serif;">Cart no.:  {{cartDetails[0]['cartid']}}</h3>
[Thu Mar 24 19:53:05.177123 2022] [wsgi:error] [pid 23432:tid 139778513557248] [client 123.203.49.113:57124]   File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 455, in getitem
[Thu Mar 24 19:53:05.177126 2022] [wsgi:error] [pid 23432:tid 139778513557248] [client 123.203.49.113:57124]     return obj[argument]
[Thu Mar 24 19:53:05.177129 2022] [wsgi:error] [pid 23432:tid 139778513557248] [client 123.203.49.113:57124] jinja2.exceptions.UndefinedError: 'cartDetails' is undefined
[Thu Mar 24 19:53:16.653451 2022] [wsgi:error] [pid 23508:tid 139897067263744] [client 123.203.49.113:57125] [2022-03-24 19:53:16,652] ERROR in app: Exception on /checkout [GET]
[Thu Mar 24 19:53:16.653489 2022] [wsgi:error] [pid 23508:tid 139897067263744] [client 123.203.49.113:57125] Traceback (most recent call last):
[Thu Mar 24 19:53:16.653493 2022] [wsgi:error] [pid 23508:tid 139897067263744] [client 123.203.49.113:57125]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app
[Thu Mar 24 19:53:16.653497 2022] [wsgi:error] [pid 23508:tid 139897067263744] [client 123.203.49.113:57125]     response = self.full_dispatch_request()
[Thu Mar 24 19:53:16.653500 2022] [wsgi:error] [pid 23508:tid 139897067263744] [client 123.203.49.113:57125]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request
[Thu Mar 24 19:53:16.653504 2022] [wsgi:error] [pid 23508:tid 139897067263744] [client 123.203.49.113:57125]     rv = self.handle_user_exception(e)
[Thu Mar 24 19:53:16.653507 2022] [wsgi:error] [pid 23508:tid 139897067263744] [client 123.203.49.113:57125]   File "/usr/local/lib/python3.8/dist-packages/flask_restful/__init__.py", line 271, in error_router
[Thu Mar 24 19:53:16.653510 2022] [wsgi:error] [pid 23508:tid 139897067263744] [client 123.203.49.113:57125]     return original_handler(e)
[Thu Mar 24 19:53:16.653513 2022] [wsgi:error] [pid 23508:tid 139897067263744] [client 123.203.49.113:57125]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request
[Thu Mar 24 19:53:16.653516 2022] [wsgi:error] [pid 23508:tid 139897067263744] [client 123.203.49.113:57125]     rv = self.dispatch_request()
[Thu Mar 24 19:53:16.653519 2022] [wsgi:error] [pid 23508:tid 139897067263744] [client 123.203.49.113:57125]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request
[Thu Mar 24 19:53:16.653533 2022] [wsgi:error] [pid 23508:tid 139897067263744] [client 123.203.49.113:57125]     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
[Thu Mar 24 19:53:16.653537 2022] [wsgi:error] [pid 23508:tid 139897067263744] [client 123.203.49.113:57125]   File "/var/www/html/init.py", line 180, in checkout
[Thu Mar 24 19:53:16.653540 2022] [wsgi:error] [pid 23508:tid 139897067263744] [client 123.203.49.113:57125]     return render_template('checkout.html' )
[Thu Mar 24 19:53:16.653551 2022] [wsgi:error] [pid 23508:tid 139897067263744] [client 123.203.49.113:57125]   File "/usr/local/lib/python3.8/dist-packages/flask/templating.py", line 147, in render_template
[Thu Mar 24 19:53:16.653554 2022] [wsgi:error] [pid 23508:tid 139897067263744] [client 123.203.49.113:57125]     return _render(
[Thu Mar 24 19:53:16.653557 2022] [wsgi:error] [pid 23508:tid 139897067263744] [client 123.203.49.113:57125]   File "/usr/local/lib/python3.8/dist-packages/flask/templating.py", line 128, in _render
[Thu Mar 24 19:53:16.653560 2022] [wsgi:error] [pid 23508:tid 139897067263744] [client 123.203.49.113:57125]     rv = template.render(context)
[Thu Mar 24 19:53:16.653563 2022] [wsgi:error] [pid 23508:tid 139897067263744] [client 123.203.49.113:57125]   File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 1291, in render
[Thu Mar 24 19:53:16.653566 2022] [wsgi:error] [pid 23508:tid 139897067263744] [client 123.203.49.113:57125]     self.environment.handle_exception()
[Thu Mar 24 19:53:16.653569 2022] [wsgi:error] [pid 23508:tid 139897067263744] [client 123.203.49.113:57125]   File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 925, in handle_exception
[Thu Mar 24 19:53:16.653572 2022] [wsgi:error] [pid 23508:tid 139897067263744] [client 123.203.49.113:57125]     raise rewrite_traceback_stack(source=source)
[Thu Mar 24 19:53:16.653575 2022] [wsgi:error] [pid 23508:tid 139897067263744] [client 123.203.49.113:57125]   File "/var/www/html/templates/checkout.html", line 1, in top-level template code
[Thu Mar 24 19:53:16.653578 2022] [wsgi:error] [pid 23508:tid 139897067263744] [client 123.203.49.113:57125]     {% extends 'layout.html' %}
[Thu Mar 24 19:53:16.653581 2022] [wsgi:error] [pid 23508:tid 139897067263744] [client 123.203.49.113:57125]   File "/var/www/html/templates/layout.html", line 26, in top-level template code
[Thu Mar 24 19:53:16.653584 2022] [wsgi:error] [pid 23508:tid 139897067263744] [client 123.203.49.113:57125]     {% block body %}
[Thu Mar 24 19:53:16.653586 2022] [wsgi:error] [pid 23508:tid 139897067263744] [client 123.203.49.113:57125]   File "/var/www/html/templates/checkout.html", line 18, in block 'body'
[Thu Mar 24 19:53:16.653589 2022] [wsgi:error] [pid 23508:tid 139897067263744] [client 123.203.49.113:57125]     <h3 style="font-family: Roboto, serif;">Cart no.:  {{cartDetails[0]['cartid']}}</h3>
[Thu Mar 24 19:53:16.653592 2022] [wsgi:error] [pid 23508:tid 139897067263744] [client 123.203.49.113:57125]   File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 455, in getitem
[Thu Mar 24 19:53:16.653595 2022] [wsgi:error] [pid 23508:tid 139897067263744] [client 123.203.49.113:57125]     return obj[argument]
[Thu Mar 24 19:53:16.653598 2022] [wsgi:error] [pid 23508:tid 139897067263744] [client 123.203.49.113:57125] jinja2.exceptions.UndefinedError: 'cartDetails' is undefined
[Thu Mar 24 19:53:48.011173 2022] [wsgi:error] [pid 23508:tid 139897050478336] [client 123.203.49.113:57127] [2022-03-24 19:53:48,010] ERROR in app: Exception on /checkout [GET]
[Thu Mar 24 19:53:48.011198 2022] [wsgi:error] [pid 23508:tid 139897050478336] [client 123.203.49.113:57127] Traceback (most recent call last):
[Thu Mar 24 19:53:48.011202 2022] [wsgi:error] [pid 23508:tid 139897050478336] [client 123.203.49.113:57127]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app
[Thu Mar 24 19:53:48.011205 2022] [wsgi:error] [pid 23508:tid 139897050478336] [client 123.203.49.113:57127]     response = self.full_dispatch_request()
[Thu Mar 24 19:53:48.011208 2022] [wsgi:error] [pid 23508:tid 139897050478336] [client 123.203.49.113:57127]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request
[Thu Mar 24 19:53:48.011212 2022] [wsgi:error] [pid 23508:tid 139897050478336] [client 123.203.49.113:57127]     rv = self.handle_user_exception(e)
[Thu Mar 24 19:53:48.011215 2022] [wsgi:error] [pid 23508:tid 139897050478336] [client 123.203.49.113:57127]   File "/usr/local/lib/python3.8/dist-packages/flask_restful/__init__.py", line 271, in error_router
[Thu Mar 24 19:53:48.011227 2022] [wsgi:error] [pid 23508:tid 139897050478336] [client 123.203.49.113:57127]     return original_handler(e)
[Thu Mar 24 19:53:48.011230 2022] [wsgi:error] [pid 23508:tid 139897050478336] [client 123.203.49.113:57127]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request
[Thu Mar 24 19:53:48.011233 2022] [wsgi:error] [pid 23508:tid 139897050478336] [client 123.203.49.113:57127]     rv = self.dispatch_request()
[Thu Mar 24 19:53:48.011236 2022] [wsgi:error] [pid 23508:tid 139897050478336] [client 123.203.49.113:57127]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request
[Thu Mar 24 19:53:48.011239 2022] [wsgi:error] [pid 23508:tid 139897050478336] [client 123.203.49.113:57127]     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
[Thu Mar 24 19:53:48.011242 2022] [wsgi:error] [pid 23508:tid 139897050478336] [client 123.203.49.113:57127]   File "/var/www/html/init.py", line 180, in checkout
[Thu Mar 24 19:53:48.011245 2022] [wsgi:error] [pid 23508:tid 139897050478336] [client 123.203.49.113:57127]     return render_template('checkout.html')
[Thu Mar 24 19:53:48.011248 2022] [wsgi:error] [pid 23508:tid 139897050478336] [client 123.203.49.113:57127]   File "/usr/local/lib/python3.8/dist-packages/flask/templating.py", line 147, in render_template
[Thu Mar 24 19:53:48.011251 2022] [wsgi:error] [pid 23508:tid 139897050478336] [client 123.203.49.113:57127]     return _render(
[Thu Mar 24 19:53:48.011254 2022] [wsgi:error] [pid 23508:tid 139897050478336] [client 123.203.49.113:57127]   File "/usr/local/lib/python3.8/dist-packages/flask/templating.py", line 128, in _render
[Thu Mar 24 19:53:48.011257 2022] [wsgi:error] [pid 23508:tid 139897050478336] [client 123.203.49.113:57127]     rv = template.render(context)
[Thu Mar 24 19:53:48.011260 2022] [wsgi:error] [pid 23508:tid 139897050478336] [client 123.203.49.113:57127]   File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 1291, in render
[Thu Mar 24 19:53:48.011263 2022] [wsgi:error] [pid 23508:tid 139897050478336] [client 123.203.49.113:57127]     self.environment.handle_exception()
[Thu Mar 24 19:53:48.011266 2022] [wsgi:error] [pid 23508:tid 139897050478336] [client 123.203.49.113:57127]   File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 925, in handle_exception
[Thu Mar 24 19:53:48.011269 2022] [wsgi:error] [pid 23508:tid 139897050478336] [client 123.203.49.113:57127]     raise rewrite_traceback_stack(source=source)
[Thu Mar 24 19:53:48.011272 2022] [wsgi:error] [pid 23508:tid 139897050478336] [client 123.203.49.113:57127]   File "/var/www/html/templates/checkout.html", line 1, in top-level template code
[Thu Mar 24 19:53:48.011275 2022] [wsgi:error] [pid 23508:tid 139897050478336] [client 123.203.49.113:57127]     {% extends 'layout.html' %}
[Thu Mar 24 19:53:48.011278 2022] [wsgi:error] [pid 23508:tid 139897050478336] [client 123.203.49.113:57127]   File "/var/www/html/templates/layout.html", line 26, in top-level template code
[Thu Mar 24 19:53:48.011281 2022] [wsgi:error] [pid 23508:tid 139897050478336] [client 123.203.49.113:57127]     {% block body %}
[Thu Mar 24 19:53:48.011283 2022] [wsgi:error] [pid 23508:tid 139897050478336] [client 123.203.49.113:57127]   File "/var/www/html/templates/checkout.html", line 18, in block 'body'
[Thu Mar 24 19:53:48.011286 2022] [wsgi:error] [pid 23508:tid 139897050478336] [client 123.203.49.113:57127]     <h3 style="font-family: Roboto, serif;">Cart no.:  {{cartDetails[0]['cartid']}}</h3>
[Thu Mar 24 19:53:48.011289 2022] [wsgi:error] [pid 23508:tid 139897050478336] [client 123.203.49.113:57127]   File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 455, in getitem
[Thu Mar 24 19:53:48.011292 2022] [wsgi:error] [pid 23508:tid 139897050478336] [client 123.203.49.113:57127]     return obj[argument]
[Thu Mar 24 19:53:48.011295 2022] [wsgi:error] [pid 23508:tid 139897050478336] [client 123.203.49.113:57127] jinja2.exceptions.UndefinedError: 'cartDetails' is undefined
[Thu Mar 24 19:53:59.073278 2022] [wsgi:error] [pid 23507:tid 139897042085632] [client 123.203.49.113:57129] [2022-03-24 19:53:59,071] ERROR in app: Exception on /checkout [GET]
[Thu Mar 24 19:53:59.073314 2022] [wsgi:error] [pid 23507:tid 139897042085632] [client 123.203.49.113:57129] Traceback (most recent call last):
[Thu Mar 24 19:53:59.073317 2022] [wsgi:error] [pid 23507:tid 139897042085632] [client 123.203.49.113:57129]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app
[Thu Mar 24 19:53:59.073321 2022] [wsgi:error] [pid 23507:tid 139897042085632] [client 123.203.49.113:57129]     response = self.full_dispatch_request()
[Thu Mar 24 19:53:59.073324 2022] [wsgi:error] [pid 23507:tid 139897042085632] [client 123.203.49.113:57129]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request
[Thu Mar 24 19:53:59.073328 2022] [wsgi:error] [pid 23507:tid 139897042085632] [client 123.203.49.113:57129]     rv = self.handle_user_exception(e)
[Thu Mar 24 19:53:59.073331 2022] [wsgi:error] [pid 23507:tid 139897042085632] [client 123.203.49.113:57129]   File "/usr/local/lib/python3.8/dist-packages/flask_restful/__init__.py", line 271, in error_router
[Thu Mar 24 19:53:59.073334 2022] [wsgi:error] [pid 23507:tid 139897042085632] [client 123.203.49.113:57129]     return original_handler(e)
[Thu Mar 24 19:53:59.073337 2022] [wsgi:error] [pid 23507:tid 139897042085632] [client 123.203.49.113:57129]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request
[Thu Mar 24 19:53:59.073340 2022] [wsgi:error] [pid 23507:tid 139897042085632] [client 123.203.49.113:57129]     rv = self.dispatch_request()
[Thu Mar 24 19:53:59.073342 2022] [wsgi:error] [pid 23507:tid 139897042085632] [client 123.203.49.113:57129]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request
[Thu Mar 24 19:53:59.073345 2022] [wsgi:error] [pid 23507:tid 139897042085632] [client 123.203.49.113:57129]     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
[Thu Mar 24 19:53:59.073349 2022] [wsgi:error] [pid 23507:tid 139897042085632] [client 123.203.49.113:57129]   File "/var/www/html/init.py", line 180, in checkout
[Thu Mar 24 19:53:59.073351 2022] [wsgi:error] [pid 23507:tid 139897042085632] [client 123.203.49.113:57129]     return render_template('checkout.html')
[Thu Mar 24 19:53:59.073354 2022] [wsgi:error] [pid 23507:tid 139897042085632] [client 123.203.49.113:57129]   File "/usr/local/lib/python3.8/dist-packages/flask/templating.py", line 147, in render_template
[Thu Mar 24 19:53:59.073357 2022] [wsgi:error] [pid 23507:tid 139897042085632] [client 123.203.49.113:57129]     return _render(
[Thu Mar 24 19:53:59.073360 2022] [wsgi:error] [pid 23507:tid 139897042085632] [client 123.203.49.113:57129]   File "/usr/local/lib/python3.8/dist-packages/flask/templating.py", line 128, in _render
[Thu Mar 24 19:53:59.073363 2022] [wsgi:error] [pid 23507:tid 139897042085632] [client 123.203.49.113:57129]     rv = template.render(context)
[Thu Mar 24 19:53:59.073366 2022] [wsgi:error] [pid 23507:tid 139897042085632] [client 123.203.49.113:57129]   File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 1291, in render
[Thu Mar 24 19:53:59.073369 2022] [wsgi:error] [pid 23507:tid 139897042085632] [client 123.203.49.113:57129]     self.environment.handle_exception()
[Thu Mar 24 19:53:59.073372 2022] [wsgi:error] [pid 23507:tid 139897042085632] [client 123.203.49.113:57129]   File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 925, in handle_exception
[Thu Mar 24 19:53:59.073375 2022] [wsgi:error] [pid 23507:tid 139897042085632] [client 123.203.49.113:57129]     raise rewrite_traceback_stack(source=source)
[Thu Mar 24 19:53:59.073378 2022] [wsgi:error] [pid 23507:tid 139897042085632] [client 123.203.49.113:57129]   File "/var/www/html/templates/checkout.html", line 1, in top-level template code
[Thu Mar 24 19:53:59.073388 2022] [wsgi:error] [pid 23507:tid 139897042085632] [client 123.203.49.113:57129]     {% extends 'layout.html' %}
[Thu Mar 24 19:53:59.073391 2022] [wsgi:error] [pid 23507:tid 139897042085632] [client 123.203.49.113:57129]   File "/var/www/html/templates/layout.html", line 26, in top-level template code
[Thu Mar 24 19:53:59.073394 2022] [wsgi:error] [pid 23507:tid 139897042085632] [client 123.203.49.113:57129]     {% block body %}
[Thu Mar 24 19:53:59.073397 2022] [wsgi:error] [pid 23507:tid 139897042085632] [client 123.203.49.113:57129]   File "/var/www/html/templates/checkout.html", line 18, in block 'body'
[Thu Mar 24 19:53:59.073400 2022] [wsgi:error] [pid 23507:tid 139897042085632] [client 123.203.49.113:57129]     <h3 style="font-family: Roboto, serif;">Cart no.:  {{cartDetails[0]['cartid']}}</h3>
[Thu Mar 24 19:53:59.073403 2022] [wsgi:error] [pid 23507:tid 139897042085632] [client 123.203.49.113:57129]   File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 455, in getitem
[Thu Mar 24 19:53:59.073406 2022] [wsgi:error] [pid 23507:tid 139897042085632] [client 123.203.49.113:57129]     return obj[argument]
[Thu Mar 24 19:53:59.073409 2022] [wsgi:error] [pid 23507:tid 139897042085632] [client 123.203.49.113:57129] jinja2.exceptions.UndefinedError: 'cartDetails' is undefined
[Thu Mar 24 19:54:03.826999 2022] [wsgi:error] [pid 23583:tid 140404796143360] [client 123.203.49.113:57130] [2022-03-24 19:54:03,825] ERROR in app: Exception on /checkout [GET]
[Thu Mar 24 19:54:03.827035 2022] [wsgi:error] [pid 23583:tid 140404796143360] [client 123.203.49.113:57130] Traceback (most recent call last):
[Thu Mar 24 19:54:03.827039 2022] [wsgi:error] [pid 23583:tid 140404796143360] [client 123.203.49.113:57130]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app
[Thu Mar 24 19:54:03.827042 2022] [wsgi:error] [pid 23583:tid 140404796143360] [client 123.203.49.113:57130]     response = self.full_dispatch_request()
[Thu Mar 24 19:54:03.827046 2022] [wsgi:error] [pid 23583:tid 140404796143360] [client 123.203.49.113:57130]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request
[Thu Mar 24 19:54:03.827049 2022] [wsgi:error] [pid 23583:tid 140404796143360] [client 123.203.49.113:57130]     rv = self.handle_user_exception(e)
[Thu Mar 24 19:54:03.827052 2022] [wsgi:error] [pid 23583:tid 140404796143360] [client 123.203.49.113:57130]   File "/usr/local/lib/python3.8/dist-packages/flask_restful/__init__.py", line 271, in error_router
[Thu Mar 24 19:54:03.827055 2022] [wsgi:error] [pid 23583:tid 140404796143360] [client 123.203.49.113:57130]     return original_handler(e)
[Thu Mar 24 19:54:03.827058 2022] [wsgi:error] [pid 23583:tid 140404796143360] [client 123.203.49.113:57130]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request
[Thu Mar 24 19:54:03.827061 2022] [wsgi:error] [pid 23583:tid 140404796143360] [client 123.203.49.113:57130]     rv = self.dispatch_request()
[Thu Mar 24 19:54:03.827064 2022] [wsgi:error] [pid 23583:tid 140404796143360] [client 123.203.49.113:57130]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request
[Thu Mar 24 19:54:03.827067 2022] [wsgi:error] [pid 23583:tid 140404796143360] [client 123.203.49.113:57130]     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
[Thu Mar 24 19:54:03.827070 2022] [wsgi:error] [pid 23583:tid 140404796143360] [client 123.203.49.113:57130]   File "/var/www/html/init.py", line 180, in checkout
[Thu Mar 24 19:54:03.827073 2022] [wsgi:error] [pid 23583:tid 140404796143360] [client 123.203.49.113:57130]     return render_template('checkout.html')
[Thu Mar 24 19:54:03.827075 2022] [wsgi:error] [pid 23583:tid 140404796143360] [client 123.203.49.113:57130]   File "/usr/local/lib/python3.8/dist-packages/flask/templating.py", line 147, in render_template
[Thu Mar 24 19:54:03.827078 2022] [wsgi:error] [pid 23583:tid 140404796143360] [client 123.203.49.113:57130]     return _render(
[Thu Mar 24 19:54:03.827090 2022] [wsgi:error] [pid 23583:tid 140404796143360] [client 123.203.49.113:57130]   File "/usr/local/lib/python3.8/dist-packages/flask/templating.py", line 128, in _render
[Thu Mar 24 19:54:03.827093 2022] [wsgi:error] [pid 23583:tid 140404796143360] [client 123.203.49.113:57130]     rv = template.render(context)
[Thu Mar 24 19:54:03.827096 2022] [wsgi:error] [pid 23583:tid 140404796143360] [client 123.203.49.113:57130]   File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 1291, in render
[Thu Mar 24 19:54:03.827099 2022] [wsgi:error] [pid 23583:tid 140404796143360] [client 123.203.49.113:57130]     self.environment.handle_exception()
[Thu Mar 24 19:54:03.827102 2022] [wsgi:error] [pid 23583:tid 140404796143360] [client 123.203.49.113:57130]   File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 925, in handle_exception
[Thu Mar 24 19:54:03.827104 2022] [wsgi:error] [pid 23583:tid 140404796143360] [client 123.203.49.113:57130]     raise rewrite_traceback_stack(source=source)
[Thu Mar 24 19:54:03.827107 2022] [wsgi:error] [pid 23583:tid 140404796143360] [client 123.203.49.113:57130]   File "/var/www/html/templates/checkout.html", line 1, in top-level template code
[Thu Mar 24 19:54:03.827110 2022] [wsgi:error] [pid 23583:tid 140404796143360] [client 123.203.49.113:57130]     {% extends 'layout.html' %}
[Thu Mar 24 19:54:03.827113 2022] [wsgi:error] [pid 23583:tid 140404796143360] [client 123.203.49.113:57130]   File "/var/www/html/templates/layout.html", line 26, in top-level template code
[Thu Mar 24 19:54:03.827116 2022] [wsgi:error] [pid 23583:tid 140404796143360] [client 123.203.49.113:57130]     {% block body %}
[Thu Mar 24 19:54:03.827119 2022] [wsgi:error] [pid 23583:tid 140404796143360] [client 123.203.49.113:57130]   File "/var/www/html/templates/checkout.html", line 18, in block 'body'
[Thu Mar 24 19:54:03.827122 2022] [wsgi:error] [pid 23583:tid 140404796143360] [client 123.203.49.113:57130]     <h3 style="font-family: Roboto, serif;">Cart no.:  {{cartDetails[0]['cartid']}}</h3>
[Thu Mar 24 19:54:03.827125 2022] [wsgi:error] [pid 23583:tid 140404796143360] [client 123.203.49.113:57130]   File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 455, in getitem
[Thu Mar 24 19:54:03.827128 2022] [wsgi:error] [pid 23583:tid 140404796143360] [client 123.203.49.113:57130]     return obj[argument]
[Thu Mar 24 19:54:03.827131 2022] [wsgi:error] [pid 23583:tid 140404796143360] [client 123.203.49.113:57130] jinja2.exceptions.UndefinedError: 'cartDetails' is undefined
[Thu Mar 24 19:55:06.589402 2022] [wsgi:error] [pid 23658:tid 140181101201152] [client 123.203.49.113:57136] [2022-03-24 19:55:06,587] ERROR in app: Exception on /checkout [GET]
[Thu Mar 24 19:55:06.589434 2022] [wsgi:error] [pid 23658:tid 140181101201152] [client 123.203.49.113:57136] Traceback (most recent call last):
[Thu Mar 24 19:55:06.589438 2022] [wsgi:error] [pid 23658:tid 140181101201152] [client 123.203.49.113:57136]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app
[Thu Mar 24 19:55:06.589441 2022] [wsgi:error] [pid 23658:tid 140181101201152] [client 123.203.49.113:57136]     response = self.full_dispatch_request()
[Thu Mar 24 19:55:06.589444 2022] [wsgi:error] [pid 23658:tid 140181101201152] [client 123.203.49.113:57136]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request
[Thu Mar 24 19:55:06.589447 2022] [wsgi:error] [pid 23658:tid 140181101201152] [client 123.203.49.113:57136]     rv = self.handle_user_exception(e)
[Thu Mar 24 19:55:06.589450 2022] [wsgi:error] [pid 23658:tid 140181101201152] [client 123.203.49.113:57136]   File "/usr/local/lib/python3.8/dist-packages/flask_restful/__init__.py", line 271, in error_router
[Thu Mar 24 19:55:06.589453 2022] [wsgi:error] [pid 23658:tid 140181101201152] [client 123.203.49.113:57136]     return original_handler(e)
[Thu Mar 24 19:55:06.589456 2022] [wsgi:error] [pid 23658:tid 140181101201152] [client 123.203.49.113:57136]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request
[Thu Mar 24 19:55:06.589466 2022] [wsgi:error] [pid 23658:tid 140181101201152] [client 123.203.49.113:57136]     rv = self.dispatch_request()
[Thu Mar 24 19:55:06.589469 2022] [wsgi:error] [pid 23658:tid 140181101201152] [client 123.203.49.113:57136]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request
[Thu Mar 24 19:55:06.589473 2022] [wsgi:error] [pid 23658:tid 140181101201152] [client 123.203.49.113:57136]     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
[Thu Mar 24 19:55:06.589476 2022] [wsgi:error] [pid 23658:tid 140181101201152] [client 123.203.49.113:57136]   File "/var/www/html/init.py", line 180, in checkout
[Thu Mar 24 19:55:06.589479 2022] [wsgi:error] [pid 23658:tid 140181101201152] [client 123.203.49.113:57136]     return render_template('checkout.html')
[Thu Mar 24 19:55:06.589481 2022] [wsgi:error] [pid 23658:tid 140181101201152] [client 123.203.49.113:57136]   File "/usr/local/lib/python3.8/dist-packages/flask/templating.py", line 147, in render_template
[Thu Mar 24 19:55:06.589485 2022] [wsgi:error] [pid 23658:tid 140181101201152] [client 123.203.49.113:57136]     return _render(
[Thu Mar 24 19:55:06.589487 2022] [wsgi:error] [pid 23658:tid 140181101201152] [client 123.203.49.113:57136]   File "/usr/local/lib/python3.8/dist-packages/flask/templating.py", line 128, in _render
[Thu Mar 24 19:55:06.589491 2022] [wsgi:error] [pid 23658:tid 140181101201152] [client 123.203.49.113:57136]     rv = template.render(context)
[Thu Mar 24 19:55:06.589493 2022] [wsgi:error] [pid 23658:tid 140181101201152] [client 123.203.49.113:57136]   File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 1291, in render
[Thu Mar 24 19:55:06.589496 2022] [wsgi:error] [pid 23658:tid 140181101201152] [client 123.203.49.113:57136]     self.environment.handle_exception()
[Thu Mar 24 19:55:06.589499 2022] [wsgi:error] [pid 23658:tid 140181101201152] [client 123.203.49.113:57136]   File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 925, in handle_exception
[Thu Mar 24 19:55:06.589502 2022] [wsgi:error] [pid 23658:tid 140181101201152] [client 123.203.49.113:57136]     raise rewrite_traceback_stack(source=source)
[Thu Mar 24 19:55:06.589505 2022] [wsgi:error] [pid 23658:tid 140181101201152] [client 123.203.49.113:57136]   File "/var/www/html/templates/checkout.html", line 1, in top-level template code
[Thu Mar 24 19:55:06.589508 2022] [wsgi:error] [pid 23658:tid 140181101201152] [client 123.203.49.113:57136]     {% extends 'layout.html' %}
[Thu Mar 24 19:55:06.589511 2022] [wsgi:error] [pid 23658:tid 140181101201152] [client 123.203.49.113:57136]   File "/var/www/html/templates/layout.html", line 26, in top-level template code
[Thu Mar 24 19:55:06.589514 2022] [wsgi:error] [pid 23658:tid 140181101201152] [client 123.203.49.113:57136]     {% block body %}
[Thu Mar 24 19:55:06.589517 2022] [wsgi:error] [pid 23658:tid 140181101201152] [client 123.203.49.113:57136]   File "/var/www/html/templates/checkout.html", line 18, in block 'body'
[Thu Mar 24 19:55:06.589520 2022] [wsgi:error] [pid 23658:tid 140181101201152] [client 123.203.49.113:57136]     <h3 style="font-family: Roboto, serif;">Cart no.:  {{cartDetails[0]['cartid']}}</h3>
[Thu Mar 24 19:55:06.589523 2022] [wsgi:error] [pid 23658:tid 140181101201152] [client 123.203.49.113:57136]   File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 455, in getitem
[Thu Mar 24 19:55:06.589526 2022] [wsgi:error] [pid 23658:tid 140181101201152] [client 123.203.49.113:57136]     return obj[argument]
[Thu Mar 24 19:55:06.589529 2022] [wsgi:error] [pid 23658:tid 140181101201152] [client 123.203.49.113:57136] jinja2.exceptions.UndefinedError: 'cartDetails' is undefined
[Thu Mar 24 19:55:40.735562 2022] [wsgi:error] [pid 23733:tid 139904678827776] [client 123.203.49.113:57138] [2022-03-24 19:55:40,731] ERROR in app: Exception on /checkout [GET]
[Thu Mar 24 19:55:40.735612 2022] [wsgi:error] [pid 23733:tid 139904678827776] [client 123.203.49.113:57138] Traceback (most recent call last):
[Thu Mar 24 19:55:40.735616 2022] [wsgi:error] [pid 23733:tid 139904678827776] [client 123.203.49.113:57138]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app
[Thu Mar 24 19:55:40.735619 2022] [wsgi:error] [pid 23733:tid 139904678827776] [client 123.203.49.113:57138]     response = self.full_dispatch_request()
[Thu Mar 24 19:55:40.735623 2022] [wsgi:error] [pid 23733:tid 139904678827776] [client 123.203.49.113:57138]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request
[Thu Mar 24 19:55:40.735626 2022] [wsgi:error] [pid 23733:tid 139904678827776] [client 123.203.49.113:57138]     rv = self.handle_user_exception(e)
[Thu Mar 24 19:55:40.735629 2022] [wsgi:error] [pid 23733:tid 139904678827776] [client 123.203.49.113:57138]   File "/usr/local/lib/python3.8/dist-packages/flask_restful/__init__.py", line 271, in error_router
[Thu Mar 24 19:55:40.735632 2022] [wsgi:error] [pid 23733:tid 139904678827776] [client 123.203.49.113:57138]     return original_handler(e)
[Thu Mar 24 19:55:40.735635 2022] [wsgi:error] [pid 23733:tid 139904678827776] [client 123.203.49.113:57138]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request
[Thu Mar 24 19:55:40.735638 2022] [wsgi:error] [pid 23733:tid 139904678827776] [client 123.203.49.113:57138]     rv = self.dispatch_request()
[Thu Mar 24 19:55:40.735641 2022] [wsgi:error] [pid 23733:tid 139904678827776] [client 123.203.49.113:57138]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request
[Thu Mar 24 19:55:40.735644 2022] [wsgi:error] [pid 23733:tid 139904678827776] [client 123.203.49.113:57138]     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
[Thu Mar 24 19:55:40.735647 2022] [wsgi:error] [pid 23733:tid 139904678827776] [client 123.203.49.113:57138]   File "/var/www/html/init.py", line 180, in checkout
[Thu Mar 24 19:55:40.735650 2022] [wsgi:error] [pid 23733:tid 139904678827776] [client 123.203.49.113:57138]     return render_template('checkout.html',cartDetails='')
[Thu Mar 24 19:55:40.735653 2022] [wsgi:error] [pid 23733:tid 139904678827776] [client 123.203.49.113:57138]   File "/usr/local/lib/python3.8/dist-packages/flask/templating.py", line 147, in render_template
[Thu Mar 24 19:55:40.735656 2022] [wsgi:error] [pid 23733:tid 139904678827776] [client 123.203.49.113:57138]     return _render(
[Thu Mar 24 19:55:40.735659 2022] [wsgi:error] [pid 23733:tid 139904678827776] [client 123.203.49.113:57138]   File "/usr/local/lib/python3.8/dist-packages/flask/templating.py", line 128, in _render
[Thu Mar 24 19:55:40.735662 2022] [wsgi:error] [pid 23733:tid 139904678827776] [client 123.203.49.113:57138]     rv = template.render(context)
[Thu Mar 24 19:55:40.735665 2022] [wsgi:error] [pid 23733:tid 139904678827776] [client 123.203.49.113:57138]   File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 1291, in render
[Thu Mar 24 19:55:40.735668 2022] [wsgi:error] [pid 23733:tid 139904678827776] [client 123.203.49.113:57138]     self.environment.handle_exception()
[Thu Mar 24 19:55:40.735672 2022] [wsgi:error] [pid 23733:tid 139904678827776] [client 123.203.49.113:57138]   File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 925, in handle_exception
[Thu Mar 24 19:55:40.735675 2022] [wsgi:error] [pid 23733:tid 139904678827776] [client 123.203.49.113:57138]     raise rewrite_traceback_stack(source=source)
[Thu Mar 24 19:55:40.735678 2022] [wsgi:error] [pid 23733:tid 139904678827776] [client 123.203.49.113:57138]   File "/var/www/html/templates/checkout.html", line 1, in top-level template code
[Thu Mar 24 19:55:40.735681 2022] [wsgi:error] [pid 23733:tid 139904678827776] [client 123.203.49.113:57138]     {% extends 'layout.html' %}
[Thu Mar 24 19:55:40.735684 2022] [wsgi:error] [pid 23733:tid 139904678827776] [client 123.203.49.113:57138]   File "/var/www/html/templates/layout.html", line 26, in top-level template code
[Thu Mar 24 19:55:40.735690 2022] [wsgi:error] [pid 23733:tid 139904678827776] [client 123.203.49.113:57138]     {% block body %}
[Thu Mar 24 19:55:40.735693 2022] [wsgi:error] [pid 23733:tid 139904678827776] [client 123.203.49.113:57138]   File "/var/www/html/templates/checkout.html", line 18, in block 'body'
[Thu Mar 24 19:55:40.735696 2022] [wsgi:error] [pid 23733:tid 139904678827776] [client 123.203.49.113:57138]     <h3 style="font-family: Roboto, serif;">Cart no.:  {{cartDetails[0]['cartid']}}</h3>
[Thu Mar 24 19:55:40.735699 2022] [wsgi:error] [pid 23733:tid 139904678827776] [client 123.203.49.113:57138]   File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 455, in getitem
[Thu Mar 24 19:55:40.735702 2022] [wsgi:error] [pid 23733:tid 139904678827776] [client 123.203.49.113:57138]     return obj[argument]
[Thu Mar 24 19:55:40.735705 2022] [wsgi:error] [pid 23733:tid 139904678827776] [client 123.203.49.113:57138] jinja2.exceptions.UndefinedError: str object has no element 0
[Sat Mar 26 01:45:50.723506 2022] [authz_core:error] [pid 48129:tid 140447963928320] [client 45.33.101.246:35866] AH01630: client denied by server configuration: /var/www/html/app.wsgi
[Sat Mar 26 12:55:37.653083 2022] [core:error] [pid 48128:tid 140447972321024] [client 161.35.86.181:56218] AH00126: Invalid URI in request GET /cgi-bin/.%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/etc/hosts HTTP/1.1
